const PEOPLE = {
  yesugei: {
    name: 'ᠶᠢᠰᠦᠭᠡᠢ',
    alias: 'ᠲᠡᠮᠦᠵᠢᠨ ᠦ ᠡᠴᠢᠭᠡ',
    years: '12 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠡᠷᠲᠡᠨ ᠦ ᠲᠠᠯ᠎ᠠ ᠨᠤᠲᠤᠭ',
    pos: [530, 80],
    power: [270, 80],
    summary:
      'ᠮᠣᠩᠭᠣᠯ ᠠᠶᠢᠮᠠᠭ ᠤᠨ ᠠᠬᠠᠯᠠᠭᠴᠢ᠂ ᠲᠡᠮᠦᠵᠢᠨ ᠦ ᠡᠴᠢᠭᠡ᠃ ᠲᠡᠭᠦᠨ ᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠭᠡᠷ ᠪᠦᠯᠢ ᠨᠢ ᠬᠦᠨᠳᠦ ᠪᠠᠶᠢᠳᠠᠯ ᠳᠤ ᠣᠷᠣᠵᠠᠢ᠃',
    note: 'ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠣᠨ ᠤ ᠲᠤᠬᠠᠢ ᠠᠳᠠᠯᠢ ᠪᠤᠰᠤ ᠪᠢᠴᠢᠯᠭᠡ ᠪᠤᠢ᠃',
    sources: ['yuan1', 'shm50', 'wiki-yesugei-en', 'wiki-yesugei-mn'],
  },
  hoelun: {
    name: 'ᠥᠭᠡᠯᠦᠨ',
    alias: 'ᠲᠡᠮᠦᠵᠢᠨ ᠦ ᠡᠬᠡ',
    years: '12—13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠡᠷᠲᠡᠨ ᠦ ᠲᠠᠯ᠎ᠠ ᠨᠤᠲᠤᠭ',
    pos: [760, 80],
    power: [20, 80],
    summary:
      'ᠶᠢᠰᠦᠭᠡᠢ ᠶᠢᠨ ᠬᠠᠲᠤᠨ᠂ ᠲᠡᠮᠦᠵᠢᠨ ᠦ ᠡᠬᠡ᠃ ᠶᠢᠰᠦᠭᠡᠢ ᠶᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠦᠷ᠎ᠡ ᠬᠡᠦᠬᠡᠳ ᠢᠶᠡᠨ ᠥᠰᠭᠡᠨ ᠬᠦᠮᠦᠵᠢᠭᠦᠯᠵᠡᠢ᠃',
    note: 'ᠥᠭᠡᠯᠦᠨ ᠦᠵᠢᠨ᠂ ᠥᠭᠡᠯᠦᠨ ᠡᠬᠡ ᠬᠡᠮᠡᠨ ᠪᠠᠰᠠ ᠨᠡᠷᠡᠯᠡᠳᠡᠭ᠃',
    sources: ['yuan1', 'wiki-hoelun-en', 'wiki-hoelun-mn'],
  },
  temujin: {
    name: 'ᠲᠡᠮᠦᠵᠢᠨ',
    alias: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ',
    years: '1162 ᠣᠨ ᠣᠷᠴᠢᠮ—1227',
    era: 'ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ',
    pos: [600, 300],
    power: [650, 230],
    summary:
      '1206 ᠣᠨ ᠳᠤ ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠴᠣᠯᠠ ᠳᠤ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠵᠦ᠂ ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ ᠢ ᠪᠠᠶᠢᠭᠤᠯᠪᠠ᠃ ᠲᠡᠭᠦᠨ ᠦ ᠮᠠᠨᠳᠤᠯ ᠳᠤ ᠤᠷᠤᠭ ᠲᠥᠷᠥᠯ᠂ ᠨᠥᠬᠥᠳ ᠪᠣᠯᠤᠨ ᠥᠭᠡᠷᠡᠴᠢᠯᠡᠭᠳᠡᠭᠴᠢ ᠬᠣᠯᠪᠤᠭ᠎ᠠ ᠴᠢᠬᠤᠯᠠ ᠡᠭᠦᠷᠭᠡ ᠭᠦᠢᠴᠡᠳᠬᠡᠪᠡ᠃',
    note: 'ᠲᠥᠷᠦᠭᠰᠡᠨ ᠣᠨ ᠤ ᠲᠤᠬᠠᠢ ᠠᠳᠠᠯᠢ ᠪᠤᠰᠤ ᠪᠢᠴᠢᠯᠭᠡ ᠪᠤᠢ᠃ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠦᠮᠡ ᠶᠢᠨ ᠴᠣᠯᠠ ᠶᠢ ᠬᠣᠵᠢᠮ ᠨᠡᠬᠡᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠰᠡᠨ᠃',
    sources: ['columbia', 'armouries', 'wiki-genghis-khan', 'wiki-temujin-mn'],
  },
  borte: {
    name: 'ᠪᠥᠷᠲᠡ',
    alias: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠶᠡᠬᠡ ᠬᠠᠲᠤᠨ',
    years: '12—13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠬᠠᠭᠠᠨ ᠤ ᠭᠡᠷ ᠪᠦᠯᠢ',
    pos: [830, 300],
    power: [1350, 230],
    summary:
      'ᠵᠦᠴᠢ᠂ ᠴᠠᠭᠠᠳᠠᠢ᠂ ᠥᠭᠡᠳᠡᠢ᠂ ᠲᠣᠯᠤᠢ ᠨᠠᠷ ᠤᠨ ᠡᠬᠡ᠃ ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠭᠡᠷ ᠪᠦᠯᠢ ᠪᠣᠯᠤᠨ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠡᠷᠡᠭ ᠲᠦ ᠨᠥᠯᠥᠭᠡ ᠦᠵᠡᠭᠦᠯᠵᠡᠢ᠃',
    sources: ['armouries', 'wiki-borte-en', 'wiki-borte-mn'],
  },
  jochi: {
    name: 'ᠵᠦᠴᠢ',
    alias: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠠᠬᠠᠮᠠᠳ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '12 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ ᠤ ᠰᠡᠭᠦᠯ—1225 ᠪᠤᠶᠤ 1227',
    era: 'ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [150, 540],
    power: [100, 540],
    summary: 'ᠲᠡᠭᠦᠨ ᠦ ᠪᠠᠷᠠᠭᠤᠨ ᠵᠦᠭ ᠦᠨ ᠡᠵᠡᠮᠰᠢᠯ ᠨᠤᠲᠤᠭ ᠨᠢ ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠤᠨ ᠤᠯᠤᠰ ᠤᠨ ᠦᠨᠳᠦᠰᠦ ᠪᠣᠯᠵᠠᠢ᠃',
    note: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠲᠡᠭᠦᠨ ᠢ ᠬᠥᠪᠡᠭᠦᠨ ᠢᠶᠡᠨ ᠭᠡᠵᠦ ᠬᠦᠯᠢᠶᠡᠨ ᠵᠥᠪᠰᠢᠶᠡᠭᠰᠡᠨ᠃',
    sources: ['armouries', 'iranicaJoci', 'wiki-jochi-en', 'wiki-jochi-mn'],
  },
  chagatai: {
    name: 'ᠴᠠᠭᠠᠳᠠᠢ',
    alias: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠬᠣᠶᠠᠳᠤᠭᠠᠷ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '12 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ ᠤ ᠰᠡᠭᠦᠯ—1242',
    era: 'ᠴᠠᠭᠠᠳᠠᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [390, 540],
    power: [100, 740],
    summary:
      'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠪᠣᠯᠤᠨ ᠪᠥᠷᠲᠡ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ ᠲᠥᠪ ᠠᠽᠢ ᠳᠠᠬᠢ ᠡᠵᠡᠮᠰᠢᠯ ᠨᠤᠲᠤᠭ ᠨᠢ ᠴᠠᠭᠠᠳᠠᠢ ᠶᠢᠨ ᠤᠯᠤᠰ ᠤᠨ ᠦᠨᠳᠦᠰᠦ ᠪᠣᠯᠵᠠᠢ᠃',
    note: '',
    sources: ['armouries', 'wiki-chagatai-en', 'wiki-chagatai-mn'],
  },
  ogedei: {
    name: 'ᠥᠭᠡᠳᠡᠢ',
    alias: 'ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ ᠤᠨ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1229—1241',
    era: 'ᠥᠭᠡᠳᠡᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [650, 540],
    power: [650, 520],
    summary: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠭᠤᠷᠪᠠᠳᠤᠭᠠᠷ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1229 ᠣᠨ ᠳᠤ ᠬᠤᠷᠢᠯᠳᠠᠢ ᠪᠠᠷ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠪᠡ᠃',
    note: '1227—1229 ᠣᠨ ᠳᠤ ᠲᠣᠯᠤᠢ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠡᠷᠡᠭ ᠢ ᠲᠦᠷ ᠬᠠᠮᠢᠶᠠᠷᠴᠠᠢ᠃',
    sources: ['columbia', 'armouries', 'wiki-ogedei-en', 'wiki-ogedei-mn'],
  },
  toregene: {
    name: 'ᠳᠥᠷᠡᠭᠡᠨᠡ',
    alias: 'ᠲᠥᠷᠥ ᠪᠠᠷᠢᠭᠰᠠᠨ ᠬᠠᠲᠤᠨ',
    years: 'ᠲᠥᠷᠥ ᠪᠠᠷᠢᠭᠰᠠᠨ ᠣᠨ᠄ 1241—1246',
    era: 'ᠥᠭᠡᠳᠡᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [880, 540],
    power: [1000, 620],
    summary:
      'ᠥᠭᠡᠳᠡᠢ ᠶᠢᠨ ᠬᠠᠲᠤᠨ᠂ ᠭᠦᠶᠦᠭ ᠦᠨ ᠡᠬᠡ᠃ ᠥᠭᠡᠳᠡᠢ ᠶᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠡᠷᠡᠭ ᠢ ᠬᠠᠮᠢᠶᠠᠷᠵᠤ᠂ ᠭᠦᠶᠦᠭ ᠢ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠬᠦ ᠳᠦ ᠴᠢᠬᠤᠯᠠ ᠡᠭᠦᠷᠭᠡ ᠭᠦᠢᠴᠡᠳᠬᠡᠪᠡ᠃',
    note: 'ᠥᠪᠡᠷ ᠦᠨ ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠶᠢᠨ ᠨᠥᠯᠥᠭᠡ ᠲᠡᠢ ᠪᠠᠶᠢᠪᠠ᠃',
    sources: ['armouries', 'wiki-toregene', 'wiki-toregene-mn'],
  },
  tolui: {
    name: 'ᠲᠣᠯᠤᠢ',
    alias: 'ᠶᠡᠬᠡ ᠨᠣᠶᠠᠨ',
    years: 'ᠲᠥᠷᠥ ᠬᠠᠮᠢᠶᠠᠷᠤᠭᠰᠠᠨ ᠣᠨ᠄ 1227—1229',
    era: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [1230, 540],
    power: [1000, 390],
    summary:
      'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠪᠣᠯᠤᠨ ᠪᠥᠷᠲᠡ ᠶᠢᠨ ᠳᠥᠷᠪᠡᠳᠦᠭᠡᠷ ᠬᠥᠪᠡᠭᠦᠨ᠃ ᠮᠥᠩᠬᠡ᠂ ᠬᠤᠪᠢᠯᠠᠢ᠂ ᠬᠦᠯᠡᠭᠦ᠂ ᠠᠷᠢᠭᠪᠥᠬᠡ ᠨᠠᠷ ᠤᠨ ᠡᠴᠢᠭᠡ᠃',
    note: 'ᠬᠣᠵᠢᠮ ᠬᠠᠭᠠᠨ ᠴᠣᠯᠠ ᠨᠡᠬᠡᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠰᠡᠨ᠃',
    sources: ['yuan115', 'armouries', 'wiki-tolui-en', 'wiki-tolui-mn'],
  },
  sorghaghtani: {
    name: 'ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ',
    alias: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠬᠠᠲᠤᠨ',
    years: '12 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ ᠤ ᠰᠡᠭᠦᠯ—1252',
    era: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [1480, 540],
    power: [1000, 980],
    summary:
      'ᠮᠥᠩᠬᠡ᠂ ᠬᠤᠪᠢᠯᠠᠢ᠂ ᠬᠦᠯᠡᠭᠦ᠂ ᠠᠷᠢᠭᠪᠥᠬᠡ ᠨᠠᠷ ᠤᠨ ᠡᠬᠡ᠃ ᠬᠥᠪᠡᠭᠦᠳ ᠦᠨ ᠢᠶᠡᠨ ᠬᠦᠮᠦᠵᠢᠯ ᠪᠣᠯᠤᠨ ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠤᠨ ᠮᠠᠨᠳᠤᠯ ᠳᠤ ᠴᠢᠬᠤᠯᠠ ᠡᠭᠦᠷᠭᠡ ᠭᠦᠢᠴᠡᠳᠬᠡᠪᠡ᠃',
    sources: ['cambridge', 'armouries', 'wiki-sorghaghtani-en', 'wiki-sorghaghtani-mn'],
  },
  guyuk: {
    name: 'ᠭᠦᠶᠦᠭ',
    alias: 'ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ ᠤᠨ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1246—1248',
    era: 'ᠥᠭᠡᠳᠡᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [650, 790],
    power: [650, 810],
    summary: 'ᠥᠭᠡᠳᠡᠢ ᠪᠣᠯᠤᠨ ᠳᠥᠷᠡᠭᠡᠨᠡ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1246 ᠣᠨ ᠳᠤ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠪᠡ᠃',
    note: 'ᠭᠦᠶᠦᠭ ᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠣᠭᠤᠯ ᠬᠠᠢᠮᠢᠰᠢ ᠬᠠᠲᠤᠨ ᠲᠦᠷ ᠲᠥᠷᠥ ᠪᠠᠷᠢᠵᠠᠢ᠃',
    sources: ['armouries', 'wiki-guyuk-en', 'wiki-guyuk-mn'],
  },
  mongke: {
    name: 'ᠮᠥᠩᠬᠡ',
    alias: 'ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ ᠤᠨ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1251—1259',
    era: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [990, 790],
    power: [650, 1090],
    summary:
      'ᠲᠣᠯᠤᠢ ᠪᠣᠯᠤᠨ ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1251 ᠣᠨ ᠳᠤ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠭᠰᠠᠨ ᠢᠶᠠᠷ ᠬᠠᠭᠠᠨ ᠤ ᠡᠷᠬᠡ ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠳᠤ ᠰᠢᠯᠵᠢᠪᠡ᠃',
    note: '',
    sources: ['armouries', 'cambridge', 'yuan3', 'dunnell2023', 'wiki-mongke-en', 'wiki-mongke-mn'],
  },
  kublai: {
    name: 'ᠬᠤᠪᠢᠯᠠᠢ',
    alias: 'ᠰᠡᠴᠡᠨ ᠬᠠᠭᠠᠨ',
    years: '1215—1294',
    era: 'ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠡᠵᠡᠨᠲᠦ ᠭᠦᠷᠦᠨ ᠪᠠ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    pos: [1260, 790],
    power: [650, 1400],
    summary:
      '1260 ᠣᠨ ᠳᠤ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠵᠦ᠂ ᠠᠷᠢᠭᠪᠥᠬᠡ ᠲᠡᠢ ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠪᠤᠯᠢᠶᠠᠯᠳᠤᠪᠠ᠃ 1271 ᠣᠨ ᠳᠤ ᠶᠡᠬᠡ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠬᠡᠮᠡᠬᠦ ᠨᠡᠷ᠎ᠡ ᠶᠢ ᠬᠡᠷᠡᠭᠯᠡᠪᠡ᠃',
    note: '1260 ᠣᠨ ᠳᠤ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠭᠰᠠᠨ᠂ 1271 ᠣᠨ ᠳᠤ ᠤᠯᠤᠰ ᠤᠨ ᠨᠡᠷ᠎ᠡ ᠶᠢ ᠲᠣᠭᠲᠠᠭᠠᠭᠰᠠᠨ᠂ 1279 ᠣᠨ ᠳᠤ ᠡᠮᠦᠨᠡᠲᠦ ᠰᠦᠩ ᠤᠯᠤᠰ ᠮᠥᠬᠦᠭᠰᠡᠨ ᠨᠢ ᠭᠤᠷᠪᠠᠨ ᠥᠭᠡᠷ᠎ᠡ ᠦᠢᠯᠡ ᠶᠠᠪᠤᠳᠠᠯ ᠶᠤᠮ᠃',
    sources: ['cambridge', 'met', 'wiki-kublai-en', 'wiki-kublai-mn'],
  },
  chabi: {
    name: 'ᠴᠠᠪᠢ',
    alias: 'ᠬᠤᠪᠢᠯᠠᠢ ᠶᠢᠨ ᠬᠠᠲᠤᠨ',
    years: '13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ—1281',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠣᠷᠳᠣᠨ',
    pos: [1490, 790],
    power: [1050, 1400],
    summary:
      'ᠴᠢᠩᠭᠢᠮ ᠦᠨ ᠡᠬᠡ᠃ ᠬᠤᠪᠢᠯᠠᠢ ᠶᠢᠨ ᠣᠷᠳᠣᠨ ᠤ ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠪᠣᠯᠤᠨ ᠱᠠᠰᠢᠨ ᠤ ᠬᠡᠷᠡᠭ ᠲᠦ ᠨᠥᠯᠥᠭᠡ ᠲᠡᠢ ᠪᠠᠶᠢᠪᠠ᠃',
    sources: ['chabi', 'yuan115', 'wiki-chabi-en', 'wiki-chabi-mn'],
  },
  ariq: {
    name: 'ᠠᠷᠢᠭᠪᠥᠬᠡ',
    alias: 'ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢᠨ ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ',
    years: 'ᠰᠢᠷᠡᠭᠡ ᠪᠤᠯᠢᠶᠠᠯᠳᠤᠭᠰᠠᠨ ᠣᠨ᠄ 1260—1264',
    era: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    pos: [2010, 790],
    power: [1040, 1210],
    summary:
      'ᠲᠣᠯᠤᠢ ᠪᠣᠯᠤᠨ ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1260 ᠣᠨ ᠳᠤ ᠬᠤᠪᠢᠯᠠᠢ ᠠᠴᠠ ᠲᠤᠰᠳᠠᠭᠠᠷ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠵᠦ᠂ ᠠᠬᠠ ᠲᠠᠢ ᠪᠠᠨ ᠳᠠᠶᠢᠯᠳᠤᠪᠠ᠃',
    sources: ['cambridge', 'armouries', 'wiki-ariq-en', 'wiki-ariq-mn'],
  },
  zhenjin: {
    name: 'ᠴᠢᠩᠭᠢᠮ',
    alias: 'ᠬᠤᠩᠲᠠᠶᠢᠵᠢ',
    years: '13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠬᠠᠭᠠᠨ ᠤᠳᠤᠮ',
    pos: [1260, 1040],
    power: [300, 1660],
    summary:
      'ᠬᠤᠪᠢᠯᠠᠢ ᠪᠣᠯᠤᠨ ᠴᠠᠪᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1273 ᠣᠨ ᠳᠤ ᠬᠤᠩᠲᠠᠶᠢᠵᠢ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠭᠰᠡᠨ ᠪᠣᠯᠪᠠᠴᠤ ᠡᠴᠢᠭᠡ ᠡᠴᠡ ᠪᠡᠨ ᠤᠷᠢᠳ᠎ᠠ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠪᠠ᠃',
    note: 'ᠬᠠᠭᠠᠨ ᠴᠣᠯᠠ ᠶᠢ ᠬᠣᠵᠢᠮ ᠨᠡᠬᠡᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠰᠡᠨ᠃ ᠲᠡᠮᠦᠷ ᠨᠢ ᠡᠪᠦᠭᠡ ᠬᠤᠪᠢᠯᠠᠢ ᠶᠢᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠪᠠ᠃',
    sources: ['yuan115', 'wiki-zhenjin-en', 'wiki-zhenjin-mn'],
  },
  temur: {
    name: 'ᠲᠡᠮᠦᠷ',
    alias: 'ᠥᠯᠵᠡᠶᠢᠲᠦ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1294—1307',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    pos: [1090, 1290],
    power: [650, 1690],
    summary:
      'ᠴᠢᠩᠭᠢᠮ ᠦᠨ ᠭᠤᠷᠪᠠᠳᠤᠭᠠᠷ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠬᠤᠪᠢᠯᠠᠢ ᠶᠢᠨ ᠠᠴᠢ᠃ 1294 ᠣᠨ ᠳᠤ ᠡᠪᠦᠭᠡ ᠶᠢᠨ ᠢᠶᠡᠨ ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠪᠠ᠃',
    note: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ ᠨᠢ ᠲᠡᠮᠦᠷ ᠦᠨ ᠠᠬ᠎ᠠ ᠪᠣᠯᠣᠨ᠎ᠠ᠃',
    sources: ['yuan18', 'wiki-temur-en', 'wiki-temur-mn'],
  },
  darmabala: {
    name: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ',
    alias: 'ᠬᠠᠢᠰᠠᠨ ᠤ ᠡᠴᠢᠭᠡ',
    years: '13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠬᠠᠭᠠᠨ ᠤᠳᠤᠮ',
    pos: [1460, 1290],
    power: [1090, 1690],
    summary: 'ᠴᠢᠩᠭᠢᠮ ᠦᠨ ᠬᠣᠶᠠᠳᠤᠭᠠᠷ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠬᠠᠢᠰᠠᠨ ᠤ ᠡᠴᠢᠭᠡ᠃ ᠲᠡᠮᠦᠷ ᠦᠨ ᠠᠬ᠎ᠠ᠃',
    note: 'ᠬᠠᠭᠠᠨ ᠴᠣᠯᠠ ᠶᠢ ᠬᠣᠵᠢᠮ ᠨᠡᠬᠡᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠰᠡᠨ᠃',
    sources: ['yuan115', 'yuan22', 'wiki-darmabala-en', 'wiki-darmabala-mn'],
  },
  qaishan: {
    name: 'ᠬᠠᠢᠰᠠᠨ',
    alias: 'ᠬᠦᠯᠦᠭ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1307—1311',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    pos: [1460, 1510],
    power: [1090, 1890],
    summary: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ ᠲᠡᠮᠦᠷ ᠬᠠᠭᠠᠨ ᠤ ᠠᠬ᠎ᠠ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃',
    sources: ['yuan22', 'wiki-qaishan-en', 'wiki-qaishan-mn'],
  },
  kusala: {
    name: 'ᠬᠦᠰᠡᠯᠡ',
    alias: 'ᠬᠤᠲᠤᠭᠲᠤ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1329',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    pos: [1460, 1730],
    power: [1090, 2100],
    summary:
      'ᠬᠠᠢᠰᠠᠨ ᠤ ᠠᠬᠠᠮᠠᠳ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ ᠦᠨ ᠡᠴᠢᠭᠡ᠃ 1329 ᠣᠨ ᠳᠤ ᠪᠣᠭᠤᠨᠢ ᠬᠤᠭᠤᠴᠠᠭᠠᠨ ᠳᠤ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ᠃',
    note: 'ᠬᠠᠢᠰᠠᠨ ᠪᠣᠯᠤᠨ ᠬᠦᠰᠡᠯᠡ ᠶᠢᠨ ᠵᠠᠭᠤᠷ᠎ᠠ ᠪᠤᠰᠤᠳ ᠬᠠᠭᠠᠳ ᠰᠠᠭᠤᠭᠰᠠᠨ᠃',
    sources: ['yuan31', 'wiki-kusala-en', 'wiki-kusala-mn'],
  },
  toghon: {
    name: 'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ',
    alias: 'ᠤᠬᠠᠭᠠᠨᠲᠤ ᠬᠠᠭᠠᠨ',
    years: '1320—1370',
    era: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠡᠭᠦᠯ ᠦᠶ᠎ᠡ',
    pos: [1460, 1950],
    power: [650, 2100],
    summary:
      '1333 ᠣᠨ ᠳᠤ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ᠃ 1368 ᠣᠨ ᠳᠤ ᠳᠠᠶᠢᠳᠤ ᠡᠴᠡ ᠤᠮᠠᠷ᠎ᠠ ᠵᠦᠭ ᠤᠬᠤᠷᠴᠤ᠂ 1370 ᠣᠨ ᠬᠦᠷᠲᠡᠯ᠎ᠡ ᠲᠥᠷᠥ ᠪᠠᠷᠢᠭᠰᠠᠭᠠᠷ ᠪᠠᠶᠢᠪᠠ᠃',
    note: 'ᠳᠠᠶᠢᠳᠤ ᠡᠴᠡ ᠤᠬᠤᠷᠤᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭᠠᠬᠢ ᠦᠶ᠎ᠡ ᠶᠢ ᠤᠮᠠᠷᠠᠲᠤ ᠶᠤᠸᠠᠨ ᠬᠡᠮᠡᠨ ᠨᠡᠷᠡᠯᠡᠳᠡᠭ᠃',
    sources: ['yuan38', 'met', 'yuan114', 'wiki-toghon-en', 'wiki-toghon-mn'],
  },
  toghrul: {
    name: 'ᠲᠣᠭᠣᠷᠢᠯ',
    alias: 'ᠸᠠᠩ ᠬᠠᠨ',
    years: '12—13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠲᠠᠯ᠎ᠠ ᠨᠤᠲᠤᠭ ᠤᠨ ᠬᠣᠯᠪᠤᠭ᠎ᠠ',
    pos: [150, 80],
    power: [270, 410],
    summary:
      'ᠬᠡᠷᠡᠶᠢᠳ ᠦᠨ ᠬᠠᠨ᠂ ᠶᠢᠰᠦᠭᠡᠢ ᠶᠢᠨ ᠠᠨᠳᠠ᠃ ᠲᠡᠮᠦᠵᠢᠨ ᠢ ᠳᠡᠮᠵᠢᠵᠦ ᠪᠠᠶᠢᠭᠠᠳ ᠬᠣᠵᠢᠮ ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ ᠪᠣᠯᠵᠠᠢ᠃',
    note: 'ᠠᠨᠳᠠ ᠪᠣᠯ ᠲᠠᠩᠭᠠᠷᠢᠭ ᠤᠨ ᠬᠣᠯᠪᠤᠭ᠎ᠠ᠃',
    sources: ['isdp', 'wiki-toghrul-en', 'wiki-toghrul-mn'],
  },
  jamukha: {
    name: 'ᠵᠠᠮᠤᠬ᠎ᠠ',
    alias: 'ᠲᠡᠮᠦᠵᠢᠨ ᠦ ᠠᠨᠳᠠ ᠪᠠ ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ',
    years: '12—13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠲᠠᠯ᠎ᠠ ᠨᠤᠲᠤᠭ ᠤᠨ ᠬᠣᠯᠪᠤᠭ᠎ᠠ',
    pos: [150, 300],
    power: [1040, 80],
    summary:
      'ᠲᠡᠮᠦᠵᠢᠨ ᠲᠡᠢ ᠠᠨᠳᠠ ᠪᠣᠯᠤᠯᠴᠠᠵᠤ᠂ ᠬᠠᠮᠲᠤᠷᠠᠵᠤ ᠪᠠᠶᠢᠪᠠ᠃ ᠬᠣᠵᠢᠮ ᠲᠠᠯ᠎ᠠ ᠨᠤᠲᠤᠭ ᠤᠨ ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠶᠢᠨ ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ ᠪᠣᠯᠵᠠᠢ᠃',
    note: 'ᠬᠠᠮᠲᠤᠷᠠᠭᠴᠢ ᠪᠠ ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ ᠭᠡᠳᠡᠭ ᠬᠣᠯᠪᠤᠭ᠎ᠠ ᠴᠠᠭ ᠤᠨ ᠶᠠᠪᠤᠴᠠ ᠳᠤ ᠥᠭᠡᠷᠡᠴᠢᠯᠡᠭᠳᠡᠳᠡᠭ᠃',
    sources: ['isdp', 'wiki-jamukha-en', 'wiki-jamukha-mn'],
  },
  batu: {
    name: 'ᠪᠠᠲᠤ',
    alias: 'ᠵᠦᠴᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    summary:
      'ᠵᠦᠴᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1250—1251 ᠣᠨ ᠳᠤ ᠮᠥᠩᠬᠡ ᠶᠢ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠬᠦ ᠶᠢ ᠳᠡᠮᠵᠢᠵᠡᠢ᠃ ᠪᠠᠷᠠᠭᠤᠨ ᠵᠦᠭ ᠦᠨ ᠡᠵᠡᠮᠰᠢᠯ ᠨᠤᠲᠤᠭ ᠨᠢ ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠯᠤᠰ ᠤᠨ ᠴᠢᠬᠤᠯᠠ ᠬᠡᠰᠡᠭ ᠪᠠᠶᠢᠪᠠ᠃',
    note: 'ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠣᠨ ᠢ 1255 ᠪᠤᠶᠤ 1256 ᠭᠡᠵᠦ ᠲᠡᠮᠳᠡᠭᠯᠡᠳᠡᠭ᠃',
    sources: [
      'armouries',
      'yuan3',
      'iranicaJoci',
      'dunnell2023',
      'iranicaMongols',
      'wiki-batu-en',
      'wiki-batu-mn',
    ],
    pos: [20, 790],
    power: [180, 1090],
  },
  hulegu: {
    name: 'ᠬᠦᠯᠡᠭᠦ',
    alias: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ—1265',
    era: 'ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    summary:
      'ᠲᠣᠯᠤᠢ ᠪᠣᠯᠤᠨ ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ ᠮᠥᠩᠬᠡ ᠬᠠᠭᠠᠨ ᠤ ᠵᠠᠷᠯᠢᠭ ᠢᠶᠠᠷ ᠪᠠᠷᠠᠭᠤᠨ ᠵᠦᠭ ᠴᠡᠷᠢᠭ ᠮᠣᠷᠳᠠᠭᠤᠯᠪᠠ᠃ ᠡᠯ ᠬᠠᠨ ᠤ ᠤᠯᠤᠰ ᠤᠨ ᠦᠨᠳᠦᠰᠦ ᠶᠢ ᠲᠠᠯᠪᠢᠵᠠᠢ᠃',
    sources: ['iranicaHulagu', 'yuan3', 'iranicaChinaIran', 'wiki-hulegu-en', 'wiki-hulegu-mn'],
    pos: [1740, 790],
    power: [1350, 1410],
  },
  berke: {
    name: 'ᠪᠡᠷᠬᠡ',
    alias: 'ᠵᠦᠴᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '13 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠳᠤᠮ',
    summary:
      'ᠵᠦᠴᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠯᠤᠰ ᠢ ᠵᠠᠬᠢᠷᠴᠤ᠂ 1262—1263 ᠣᠨ ᠳᠤ ᠬᠦᠯᠡᠭᠦ ᠶᠢᠨ ᠴᠡᠷᠢᠭ ᠲᠡᠢ ᠳᠠᠶᠢᠯᠳᠤᠵᠠᠢ᠃',
    note: 'ᠲᠥᠷᠥ ᠪᠠᠷᠢᠭᠰᠠᠨ ᠣᠨ ᠢ 1257—1266 ᠪᠤᠶᠤ 1257—1267 ᠭᠡᠵᠦ ᠲᠡᠮᠳᠡᠭᠯᠡᠳᠡᠭ᠃',
    sources: [
      'iranicaJoci',
      'yuan3',
      'dunnell2023',
      'iranicaHulagu',
      'wiki-berke-en',
      'wiki-berke-mn',
    ],
    pos: [280, 790],
    power: [180, 1430],
  },
  tumbinai: {
    name: 'ᠲᠤᠮᠪᠢᠨᠠᠢ ᠰᠡᠴᠡᠨ',
    alias: 'ᠬᠠᠪᠤᠯ ᠤᠨ ᠡᠴᠢᠭᠡ',
    years: 'ᠣᠨ ᠲᠣᠳᠣᠷᠬᠠᠢ ᠦᠭᠡᠢ',
    era: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠡᠮᠦᠨᠡᠬᠢ ᠦᠶ᠎ᠡ',
    summary: '《ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠨᠢᠭᠤᠴᠠ ᠲᠣᠪᠴᠢᠶᠠᠨ》 ᠳᠤ ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ ᠤ ᠡᠴᠢᠭᠡ ᠭᠡᠵᠦ ᠲᠡᠮᠳᠡᠭᠯᠡᠵᠡᠢ᠃',
    note: 'ᠡᠨᠡ ᠤᠳᠤᠮ ᠰᠤᠳᠤᠷ ᠤᠨ ᠲᠡᠮᠳᠡᠭᠯᠡᠯ ᠳᠦ ᠲᠤᠯᠭᠤᠭᠤᠷᠢᠯᠠᠵᠠᠢ᠃',
    sources: ['shm48', 'mongoltoliKhabul', 'wiki-tumbinai-en', 'wiki-tumbinai-mn'],
    pos: [530, -670],
    power: [530, -670],
  },
  khabul: {
    name: 'ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ',
    alias: 'ᠲᠤᠮᠪᠢᠨᠠᠢ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '12 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠡᠮᠦᠨᠡᠬᠢ ᠦᠶ᠎ᠡ',
    summary:
      '《ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠨᠢᠭᠤᠴᠠ ᠲᠣᠪᠴᠢᠶᠠᠨ》 ᠳᠤ ᠲᠤᠮᠪᠢᠨᠠᠢ ᠰᠡᠴᠡᠨ ᠦ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠪᠠᠷᠲᠠᠨ ᠪᠠᠭᠠᠲᠤᠷ ᠤᠨ ᠡᠴᠢᠭᠡ ᠭᠡᠵᠦ ᠲᠡᠮᠳᠡᠭᠯᠡᠵᠡᠢ᠃ ᠬᠠᠮᠤᠭ ᠮᠣᠩᠭᠣᠯ ᠢ ᠵᠠᠬᠢᠷᠴᠤ ᠪᠠᠶᠢᠪᠠ᠃',
    note: 'ᠡᠨᠳᠡ ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ ᠦ ᠬᠣᠯᠪᠤᠭ᠎ᠠ ᠶᠢ ᠵᠢᠷᠤᠭᠯᠠᠪᠠ᠃ ᠬᠠᠪᠤᠯ ᠤᠨ ᠳᠠᠷᠠᠭ᠎ᠠ ᠠᠮᠪᠠᠭᠠᠢ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠵᠠᠢ᠃',
    sources: ['shm48', 'shm52', 'mongoltoliKhabul', 'wiki-khabul-en', 'wiki-khabul-mn'],
    pos: [530, -420],
    power: [530, -420],
  },
  bartan: {
    name: 'ᠪᠠᠷᠲᠠᠨ ᠪᠠᠭᠠᠲᠤᠷ',
    alias: 'ᠶᠢᠰᠦᠭᠡᠢ ᠶᠢᠨ ᠡᠴᠢᠭᠡ',
    years: 'ᠣᠨ ᠲᠣᠳᠣᠷᠬᠠᠢ ᠦᠭᠡᠢ',
    era: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠡᠮᠦᠨᠡᠬᠢ ᠦᠶ᠎ᠡ',
    summary:
      '《ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠨᠢᠭᠤᠴᠠ ᠲᠣᠪᠴᠢᠶᠠᠨ》 ᠳᠤ ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ ᠤ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠶᠢᠰᠦᠭᠡᠢ ᠪᠠᠭᠠᠲᠤᠷ ᠤᠨ ᠡᠴᠢᠭᠡ ᠭᠡᠵᠦ ᠲᠡᠮᠳᠡᠭᠯᠡᠵᠡᠢ᠃',
    note: 'ᠡᠨᠡ ᠤᠳᠤᠮ ᠰᠤᠳᠤᠷ ᠤᠨ ᠲᠡᠮᠳᠡᠭᠯᠡᠯ ᠳᠦ ᠲᠤᠯᠭᠤᠭᠤᠷᠢᠯᠠᠵᠠᠢ᠃',
    sources: ['shm48', 'shm50', 'mongoltoliYesugei', 'wiki-yesugei-en', 'wiki-bartan-mn'],
    pos: [530, -170],
    power: [530, -170],
  },
  ayushiridara: {
    name: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ',
    alias: 'ᠪᠢᠯᠢᠭᠲᠦ ᠬᠠᠭᠠᠨ',
    years: 'ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠭᠰᠠᠨ ᠣᠨ᠄ 1370—1378',
    era: 'ᠤᠮᠠᠷᠠᠲᠤ ᠶᠤᠸᠠᠨ',
    summary:
      'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ ᠦᠨ ᠬᠥᠪᠡᠭᠦᠨ᠃ 1370 ᠣᠨ ᠳᠤ ᠡᠴᠢᠭᠡ ᠶᠢᠨ ᠢᠶᠡᠨ ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠪᠠ᠃ ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠤᠨ ᠡᠴᠢᠭᠡ᠃',
    sources: [
      'yuan114',
      'mingTaizu57',
      'okada1994',
      'wiki-ayushiridara-en',
      'wiki-ayushiridara-mn',
    ],
    generationFromToghon: 1,
    pos: [1460, 2200],
    power: [650, 2380],
  },
  maidarbal: {
    name: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ',
    alias: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ',
    years: '14 ᠳᠦᠭᠡᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠤᠮᠠᠷᠠᠲᠤ ᠶᠤᠸᠠᠨ',
    summary:
      'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ ᠦᠨ ᠠᠴᠢ᠃ 1370 ᠣᠨ ᠳᠤ ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠴᠡᠷᠢᠭ ᠲᠦ ᠣᠯᠵᠠᠯᠠᠭᠳᠠᠪᠠ᠃ 1374 ᠣᠨ ᠳᠤ ᠤᠮᠠᠷ᠎ᠠ ᠪᠤᠴᠠᠭᠠᠵᠠᠢ᠃',
    note: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠤᠨ ᠦᠷ᠎ᠡ ᠬᠡᠦᠬᠡᠳ ᠦᠨ ᠲᠤᠬᠠᠢ ᠰᠤᠷᠪᠤᠯᠵᠢ ᠶᠢ ᠴᠢᠮᠪᠠᠢᠷᠠᠭᠤᠯᠤᠨ ᠰᠤᠳᠤᠯᠬᠤ ᠬᠡᠷᠡᠭᠲᠡᠢ᠃',
    sources: ['mingTaizu57', 'ming327', 'wiki-maidarbal-en', 'wiki-ayushiridara-mn'],
    generationFromToghon: 2,
    pos: [1460, 2450],
    power: [1000, 2640],
  },
};
const EDGES = [
  {
    to: 'hoelun',
    type: 'spouse',
    label: 'ᠡᠷ᠎ᠡ ᠡᠮ᠎ᠡ',
    from: 'yesugei',
    sources: ['wiki-hoelun-en', 'wiki-hoelun-mn'],
  },
  {
    to: 'borte',
    type: 'spouse',
    label: 'ᠡᠷ᠎ᠡ ᠡᠮ᠎ᠡ',
    from: 'temujin',
    sources: ['wiki-borte-en', 'wiki-borte-mn'],
  },
  {
    to: 'toregene',
    type: 'spouse',
    label: 'ᠡᠷ᠎ᠡ ᠡᠮ᠎ᠡ',
    from: 'ogedei',
    sources: ['wiki-toregene', 'wiki-toregene-mn'],
  },
  {
    to: 'sorghaghtani',
    type: 'spouse',
    label: 'ᠡᠷ᠎ᠡ ᠡᠮ᠎ᠡ',
    from: 'tolui',
    sources: ['wiki-sorghaghtani-en', 'wiki-sorghaghtani-mn'],
  },
  {
    to: 'chabi',
    type: 'spouse',
    label: 'ᠡᠷ᠎ᠡ ᠡᠮ᠎ᠡ',
    from: 'kublai',
    sources: ['wiki-chabi-en', 'wiki-chabi-mn'],
  },
  {
    to: 'temujin',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'yesugei',
    sources: ['wiki-genghis-khan', 'wiki-temujin-mn'],
  },
  {
    to: 'temujin',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'hoelun',
    sources: ['wiki-genghis-khan', 'wiki-temujin-mn'],
  },
  {
    to: 'jochi',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'temujin',
    sources: ['wiki-jochi-en', 'wiki-jochi-mn'],
  },
  {
    to: 'chagatai',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'temujin',
    sources: ['wiki-chagatai-en', 'wiki-chagatai-mn'],
  },
  {
    to: 'ogedei',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'temujin',
    sources: ['wiki-ogedei-en', 'wiki-ogedei-mn'],
  },
  {
    to: 'tolui',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'temujin',
    sources: ['wiki-tolui-en', 'wiki-tolui-mn'],
  },
  {
    to: 'jochi',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'borte',
    sources: ['wiki-jochi-en', 'wiki-jochi-mn'],
  },
  {
    to: 'chagatai',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'borte',
    sources: ['wiki-chagatai-en', 'wiki-chagatai-mn'],
  },
  {
    to: 'ogedei',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'borte',
    sources: ['wiki-ogedei-en', 'wiki-ogedei-mn'],
  },
  {
    to: 'tolui',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'borte',
    sources: ['wiki-tolui-en', 'wiki-tolui-mn'],
  },
  {
    to: 'guyuk',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'ogedei',
    sources: ['wiki-guyuk-en', 'wiki-guyuk-mn'],
  },
  {
    to: 'guyuk',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'toregene',
    sources: ['wiki-guyuk-en', 'wiki-guyuk-mn'],
  },
  {
    to: 'mongke',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'tolui',
    sources: ['wiki-mongke-en', 'wiki-mongke-mn'],
  },
  {
    to: 'kublai',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'tolui',
    sources: ['wiki-kublai-en', 'wiki-kublai-mn'],
  },
  {
    to: 'ariq',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'tolui',
    sources: ['wiki-ariq-en', 'wiki-ariq-mn'],
  },
  {
    to: 'mongke',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'sorghaghtani',
    sources: ['wiki-mongke-en', 'wiki-mongke-mn'],
  },
  {
    to: 'kublai',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'sorghaghtani',
    sources: ['wiki-kublai-en', 'wiki-kublai-mn'],
  },
  {
    to: 'ariq',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'sorghaghtani',
    sources: ['wiki-ariq-en', 'wiki-ariq-mn'],
  },
  {
    to: 'zhenjin',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'kublai',
    sources: ['wiki-zhenjin-en', 'wiki-zhenjin-mn'],
  },
  {
    to: 'zhenjin',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'chabi',
    sources: ['wiki-zhenjin-en', 'wiki-zhenjin-mn'],
  },
  {
    to: 'temur',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'zhenjin',
    sources: ['wiki-temur-en', 'wiki-temur-mn'],
  },
  {
    to: 'darmabala',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'zhenjin',
    sources: ['wiki-darmabala-en', 'wiki-darmabala-mn'],
  },
  {
    to: 'qaishan',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'darmabala',
    sources: ['wiki-qaishan-en', 'wiki-qaishan-mn'],
  },
  {
    to: 'kusala',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'qaishan',
    sources: ['wiki-kusala-en', 'wiki-kusala-mn'],
  },
  {
    to: 'toghon',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    from: 'kusala',
    sources: ['wiki-toghon-en', 'wiki-toghon-mn'],
  },
  {
    to: 'ogedei',
    type: 'succession',
    label: '1229 · ᠲᠣᠯᠤᠢ ᠲᠦᠷ ᠲᠥᠷᠥ ᠬᠠᠮᠢᠶᠠᠷᠤᠭᠰᠠᠨ',
    from: 'temujin',
    sources: ['wiki-ogedei-en', 'wiki-ogedei-mn'],
  },
  {
    to: 'guyuk',
    type: 'succession',
    label: '1246 · ᠳᠥᠷᠡᠭᠡᠨᠡ ᠲᠥᠷᠥ ᠪᠠᠷᠢᠭᠰᠠᠨ',
    from: 'ogedei',
    sources: ['wiki-guyuk-en', 'wiki-guyuk-mn'],
  },
  {
    to: 'mongke',
    type: 'succession',
    label: '1251 · ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠳᠤ ᠰᠢᠯᠵᠢᠭᠰᠡᠨ',
    from: 'guyuk',
    sources: ['wiki-mongke-en', 'wiki-mongke-mn'],
  },
  {
    to: 'kublai',
    type: 'succession',
    label: '1260 · ᠰᠢᠷᠡᠭᠡ ᠪᠤᠯᠢᠶᠠᠯᠳᠤᠭᠰᠠᠨ',
    from: 'mongke',
    sources: ['wiki-kublai-en', 'wiki-kublai-mn'],
  },
  {
    to: 'temur',
    type: 'succession',
    label: '1294 · ᠡᠪᠦᠭᠡ ᠡᠴᠡ ᠠᠴᠢ ᠳᠤ',
    from: 'kublai',
    sources: ['wiki-temur-en', 'wiki-temur-mn'],
  },
  {
    to: 'toghrul',
    type: 'alliance',
    label: 'ᠠᠨᠳᠠ',
    from: 'yesugei',
    sources: ['wiki-toghrul-en', 'wiki-toghrul-mn'],
  },
  {
    to: 'jamukha',
    type: 'alliance',
    label: 'ᠠᠨᠳᠠ ／ ᠬᠠᠮᠲᠤᠷᠠᠭᠴᠢ → ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ',
    from: 'temujin',
    sources: ['wiki-jamukha-en', 'wiki-jamukha-mn'],
  },
  {
    to: 'temujin',
    type: 'alliance',
    label: 'ᠳᠡᠮᠵᠢᠭᠴᠢ → ᠥᠷᠥᠰᠥᠯᠳᠥᠭᠴᠢ',
    from: 'toghrul',
    sources: ['wiki-toghrul-en', 'wiki-toghrul-mn'],
  },
  {
    to: 'ariq',
    type: 'rival',
    label: '1260—1264 · ᠰᠢᠷᠡᠭᠡ ᠪᠤᠯᠢᠶᠠᠯᠳᠤᠭᠠᠨ',
    from: 'kublai',
    sources: ['wiki-ariq-en', 'wiki-ariq-mn'],
  },
  {
    from: 'jochi',
    to: 'batu',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['armouries', 'iranicaJoci', 'wiki-batu-en', 'wiki-batu-mn'],
  },
  {
    from: 'jochi',
    to: 'berke',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['iranicaJoci', 'wiki-berke-en', 'wiki-berke-mn'],
  },
  {
    from: 'tolui',
    to: 'hulegu',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['iranicaHulagu', 'armouries', 'wiki-hulegu-en', 'wiki-hulegu-mn'],
  },
  {
    from: 'sorghaghtani',
    to: 'hulegu',
    type: 'parent',
    label: 'ᠡᠬᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['iranicaHulagu', 'wiki-hulegu-en', 'wiki-hulegu-mn'],
  },
  {
    from: 'batu',
    to: 'mongke',
    type: 'alliance',
    label: '1250—1251 · ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠬᠦ ᠶᠢ ᠳᠡᠮᠵᠢᠭᠰᠡᠨ',
    sources: ['yuan3', 'dunnell2023', 'wiki-mongke-en', 'wiki-sorghaghtani-mn'],
    period: {
      fromYear: 1250,
      toYear: 1251,
      precision: 'year range',
      semantics: 'documented succession episode',
    },
  },
  {
    from: 'berke',
    to: 'hulegu',
    type: 'rival',
    label: '1262—1263 · ᠲᠤᠯᠤᠯᠳᠤᠭᠠᠨ',
    sources: ['iranicaHulagu', 'wiki-berke-en', 'wiki-berke-mn'],
    period: {
      fromYear: 1262,
      toYear: 1263,
      earliestPossibleStart: 'winter 1261–1262',
      precision: 'campaign window',
      semantics: 'first documented round of conflict',
    },
    route: 'lower-arc',
    routeY: 1565,
  },
  {
    from: 'tumbinai',
    to: 'khabul',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['shm48', 'mongoltoliKhabul', 'wiki-khabul-en', 'wiki-khabul-mn'],
  },
  {
    from: 'khabul',
    to: 'bartan',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['shm48', 'mongoltoliKhabul', 'wiki-yesugei-en', 'wiki-bartan-mn'],
  },
  {
    from: 'bartan',
    to: 'yesugei',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['shm50', 'mongoltoliYesugei', 'wiki-yesugei-en', 'wiki-yesugei-mn'],
  },
  {
    from: 'toghon',
    to: 'ayushiridara',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['yuan114', 'okada1994', 'wiki-ayushiridara-en', 'wiki-ayushiridara-mn'],
    certainty: 'documented',
  },
  {
    from: 'ayushiridara',
    to: 'maidarbal',
    type: 'parent',
    label: 'ᠡᠴᠢᠭᠡ ᠬᠥᠪᠡᠭᠦᠨ',
    sources: ['mingTaizu57', 'ming327', 'wiki-maidarbal-en', 'wiki-ayushiridara-mn'],
    certainty: 'documented',
  },
];
const EVENTS = [
  {
    date: '12 ᠳᠤᠭᠠᠷ ᠵᠠᠭᠤᠨ ᠤ ᠰᠡᠭᠦᠯ',
    title: 'ᠶᠢᠰᠦᠭᠡᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠪᠠ',
    people: ['yesugei', 'hoelun', 'temujin'],
    text: 'ᠬᠣᠷᠯᠠᠭᠳᠠᠭᠰᠠᠨ ᠭᠡᠵᠦ ᠰᠤᠷᠪᠤᠯᠵᠢ ᠪᠢᠴᠢᠭ ᠲᠦ ᠲᠡᠮᠳᠡᠭᠯᠡᠵᠡᠢ᠃ ᠲᠣᠳᠣᠷᠬᠠᠢ ᠣᠨ ᠤ ᠲᠤᠬᠠᠢ ᠮᠠᠷᠭᠤᠭᠠᠨ ᠪᠤᠢ᠃',
    id: 'yesugei-death',
    precision: 'period',
    sources: ['wiki-genghis-khan', 'wiki-yesugei-en', 'wiki-yesugei-mn'],
  },
  {
    date: '1206',
    title: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠪᠡ',
    people: ['temujin'],
    text: 'ᠲᠡᠮᠦᠵᠢᠨ ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠴᠣᠯᠠ ᠠᠪᠴᠤ᠂ ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ ᠪᠠᠶᠢᠭᠤᠯᠤᠭᠳᠠᠪᠠ᠃',
    id: 'mongol-empire-1206',
    startYear: 1206,
    endYear: 1206,
    precision: 'year',
    sources: ['wiki-mongol-empire', 'wiki-genghis-khan', 'wiki-temujin-mn'],
  },
  {
    date: '1227',
    title: 'ᠲᠣᠯᠤᠢ ᠲᠥᠷᠥ ᠬᠠᠮᠢᠶᠠᠷᠤᠪᠠ',
    people: ['temujin', 'tolui'],
    text: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠲᠣᠯᠤᠢ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠡᠷᠡᠭ ᠢ ᠲᠦᠷ ᠬᠠᠮᠢᠶᠠᠷᠤᠪᠠ᠃',
    id: 'tolui-regency-1227',
    startYear: 1227,
    endYear: 1227,
    precision: 'year',
    sources: ['wiki-mongol-empire', 'wiki-tolui-en', 'wiki-tolui-mn'],
  },
  {
    date: '1229',
    title: 'ᠥᠭᠡᠳᠡᠢ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ',
    people: ['ogedei', 'tolui'],
    text: '1229 ᠣᠨ ᠳᠤ ᠥᠭᠡᠳᠡᠢ ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠳᠦ ᠰᠠᠭᠤᠪᠠ᠃',
    id: 'ogedei-accession-1229',
    startYear: 1229,
    endYear: 1229,
    precision: 'year',
    sources: ['wiki-mongol-empire', 'wiki-ogedei-en', 'wiki-ogedei-mn'],
  },
  {
    date: '1241—1246',
    title: 'ᠳᠥᠷᠡᠭᠡᠨᠡ ᠲᠥᠷᠥ ᠪᠠᠷᠢᠪᠠ',
    people: ['toregene', 'guyuk'],
    text: 'ᠥᠭᠡᠳᠡᠢ ᠶᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠳᠥᠷᠡᠭᠡᠨᠡ ᠬᠠᠲᠤᠨ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠡᠷᠡᠭ ᠢ ᠬᠠᠮᠢᠶᠠᠷᠤᠪᠠ᠃',
    id: 'toregene-regency-1241',
    startYear: 1241,
    endYear: 1246,
    precision: 'range',
    sources: ['wiki-toregene', 'wiki-toregene-mn'],
  },
  {
    date: '1246',
    title: 'ᠭᠦᠶᠦᠭ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ',
    people: ['guyuk', 'toregene'],
    text: 'ᠥᠭᠡᠳᠡᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠬᠠᠭᠠᠨ ᠤ ᠡᠷᠬᠡ ᠶᠢ ᠦᠷᠭᠦᠯᠵᠢᠯᠡᠨ ᠪᠠᠷᠢᠪᠠ᠃',
    id: 'guyuk-accession-1246',
    startYear: 1246,
    endYear: 1246,
    precision: 'year',
    sources: ['wiki-mongol-empire', 'wiki-guyuk-en', 'wiki-guyuk-mn'],
  },
  {
    date: '1251',
    title: 'ᠮᠥᠩᠬᠡ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ',
    people: ['mongke', 'sorghaghtani', 'batu', 'berke'],
    text: 'ᠭᠦᠶᠦᠭ ᠦᠨ ᠳᠠᠷᠠᠭ᠎ᠠ ᠣᠭᠤᠯ ᠬᠠᠢᠮᠢᠰᠢ ᠬᠠᠲᠤᠨ ᠲᠦᠷ ᠲᠥᠷᠥ ᠪᠠᠷᠢᠵᠠᠢ᠃ ᠪᠠᠲᠤ ᠪᠣᠯᠤᠨ ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ ᠮᠥᠩᠬᠡ ᠶᠢ ᠳᠡᠮᠵᠢᠵᠡᠢ᠃ ᠪᠡᠷᠬᠡ ᠵᠦᠴᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠢ ᠲᠥᠯᠥᠭᠡᠯᠡᠨ ᠬᠤᠷᠠᠯ ᠳᠤ ᠣᠷᠣᠯᠴᠠᠪᠠ᠃ ᠬᠠᠭᠠᠨ ᠤ ᠡᠷᠬᠡ ᠲᠣᠯᠤᠢ ᠶᠢᠨ ᠤᠳᠤᠮ ᠳᠤ ᠰᠢᠯᠵᠢᠪᠡ᠃',
    sources: ['yuan3', 'dunnell2023', 'wiki-mongke-en', 'wiki-mongke-mn'],
    graphMode: 'power',
    id: 'mongke-accession-1251',
    startYear: 1251,
    endYear: 1251,
    precision: 'year',
  },
  {
    date: '1253—1256',
    title: 'ᠬᠦᠯᠡᠭᠦ ᠪᠠᠷᠠᠭᠤᠨ ᠵᠦᠭ ᠮᠣᠷᠳᠠᠪᠠ',
    people: ['hulegu', 'mongke'],
    text: 'ᠬᠦᠯᠡᠭᠦ ᠮᠥᠩᠬᠡ ᠬᠠᠭᠠᠨ ᠤ ᠵᠠᠷᠯᠢᠭ ᠢᠶᠠᠷ 1253 ᠣᠨ ᠳᠤ ᠪᠠᠷᠠᠭᠤᠨ ᠵᠦᠭ ᠮᠣᠷᠳᠠᠵᠠᠢ᠃ 1256 ᠣᠨ ᠳᠤ ᠢᠷᠠᠨ ᠳᠤ ᠴᠡᠷᠢᠭ ᠦᠨ ᠠᠵᠢᠯᠯᠠᠭ᠎ᠠ ᠶᠠᠪᠤᠭᠤᠯᠪᠠ᠃',
    sources: ['yuan3', 'iranicaHulagu', 'wiki-hulegu-en', 'wiki-hulegu-mn'],
    graphMode: 'family',
    id: 'hulegu-campaign-1253',
    startYear: 1253,
    endYear: 1256,
    precision: 'range',
  },
  {
    date: '1260—1264',
    title: 'ᠠᠬ᠎ᠠ ᠳᠡᠭᠦᠦ ᠶᠢᠨ ᠰᠢᠷᠡᠭᠡ ᠪᠤᠯᠢᠶᠠᠯᠳᠤᠭᠠᠨ',
    people: ['kublai', 'ariq'],
    text: 'ᠬᠤᠪᠢᠯᠠᠢ ᠪᠣᠯᠤᠨ ᠠᠷᠢᠭᠪᠥᠬᠡ ᠲᠤᠰ ᠲᠤᠰ ᠲᠠᠭᠠᠨ ᠬᠠᠭᠠᠨ ᠥᠷᠭᠦᠮᠵᠢᠯᠡᠭᠳᠡᠵᠦ᠂ ᠳᠣᠲᠣᠭᠠᠳᠤ ᠳᠠᠶᠢᠨ ᠡᠭᠦᠰᠪᠡ᠃',
    id: 'toluid-war-1260',
    startYear: 1260,
    endYear: 1264,
    precision: 'range',
    sources: ['wiki-mongol-empire', 'wiki-ariq-en', 'wiki-ariq-mn'],
  },
  {
    date: '1262—1263',
    title: 'ᠪᠡᠷᠬᠡ ᠪᠠ ᠬᠦᠯᠡᠭᠦ ᠶᠢᠨ ᠴᠡᠷᠢᠭ ᠦᠨ ᠲᠤᠯᠤᠯᠳᠤᠭᠠᠨ',
    people: ['berke', 'hulegu'],
    text: 'ᠪᠡᠷᠬᠡ ᠪᠣᠯᠤᠨ ᠬᠦᠯᠡᠭᠦ ᠶᠢᠨ ᠴᠡᠷᠢᠭ ᠳᠠᠶᠢᠯᠳᠤᠪᠠ᠃ ᠭᠠᠵᠠᠷ ᠨᠤᠲᠤᠭ ᠪᠠ ᠣᠷᠣᠯᠭ᠎ᠠ ᠶᠢᠨ ᠬᠤᠪᠢ ᠶᠢᠨ ᠮᠠᠷᠭᠤᠭᠠᠨ ᠨᠢ ᠵᠥᠷᠢᠴᠡᠯ ᠦᠨ ᠴᠢᠬᠤᠯᠠ ᠰᠢᠯᠲᠠᠭᠠᠨ ᠪᠠᠶᠢᠪᠠ᠃ ᠳᠠᠶᠢᠨ ᠤ ᠡᠬᠢᠯᠡᠯ ᠢ 1261—1262 ᠣᠨ ᠤ ᠥᠪᠥᠯ ᠲᠡᠢ ᠬᠣᠯᠪᠣᠨ ᠲᠠᠶᠢᠯᠪᠤᠷᠢᠯᠠᠭᠰᠠᠨ ᠰᠤᠳᠤᠯᠭ᠎ᠠ ᠪᠤᠢ᠃',
    sources: ['iranicaHulagu', 'iranicaJoci', 'wiki-berke-en', 'wiki-berke-mn'],
    graphMode: 'power',
    focusRelations: true,
    id: 'berke-hulegu-war-1262',
    startYear: 1262,
    endYear: 1263,
    precision: 'range',
  },
  {
    date: '1271',
    title: 'ᠶᠡᠬᠡ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    people: ['kublai'],
    text: 'ᠬᠤᠪᠢᠯᠠᠢ ᠶᠡᠬᠡ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠬᠡᠮᠡᠬᠦ ᠨᠡᠷ᠎ᠡ ᠶᠢ ᠲᠣᠭᠲᠠᠭᠠᠪᠠ᠃',
    id: 'yuan-name-1271',
    startYear: 1271,
    endYear: 1271,
    precision: 'year',
    sources: ['wiki-yuan', 'wiki-kublai-en', 'wiki-kublai-mn'],
  },
  {
    date: '1279',
    title: 'ᠡᠮᠦᠨᠡᠲᠦ ᠰᠦᠩ ᠤᠯᠤᠰ ᠮᠥᠬᠦᠪᠡ',
    people: ['kublai'],
    text: '1279 ᠣᠨ ᠳᠤ ᠶᠤᠸᠠᠨ ᠤ ᠴᠡᠷᠢᠭ ᠡᠮᠦᠨᠡᠲᠦ ᠰᠦᠩ ᠤᠯᠤᠰ ᠢ ᠮᠥᠬᠦᠭᠡᠪᠡ᠃',
    id: 'song-defeat-1279',
    startYear: 1279,
    endYear: 1279,
    precision: 'year',
    sources: ['wiki-yuan', 'wiki-kublai-en', 'wiki-kublai-mn'],
  },
  {
    date: '1294',
    title: 'ᠲᠡᠮᠦᠷ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ',
    people: ['temur', 'kublai', 'zhenjin'],
    text: 'ᠴᠢᠩᠭᠢᠮ ᠨᠢ ᠬᠤᠪᠢᠯᠠᠢ ᠠᠴᠠ ᠤᠷᠢᠳ᠎ᠠ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ᠃ ᠲᠡᠮᠦᠷ ᠡᠪᠦᠭᠡ ᠶᠢᠨ ᠢᠶᠡᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠪᠠ᠃',
    id: 'temur-accession-1294',
    startYear: 1294,
    endYear: 1294,
    precision: 'year',
    sources: ['wiki-yuan', 'wiki-temur-en', 'wiki-temur-mn'],
  },
  {
    date: '1368',
    title: 'ᠶᠤᠸᠠᠨ ᠤ ᠲᠥᠷᠥ ᠳᠠᠶᠢᠳᠤ ᠡᠴᠡ ᠤᠬᠤᠷᠪᠠ',
    people: ['toghon'],
    text: '1368 ᠣᠨ ᠳᠤ ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ ᠳᠠᠶᠢᠳᠤ ᠡᠴᠡ ᠤᠮᠠᠷ᠎ᠠ ᠵᠦᠭ ᠤᠬᠤᠷᠪᠠ᠃ 1370 ᠣᠨ ᠬᠦᠷᠲᠡᠯ᠎ᠡ ᠲᠥᠷᠥ ᠪᠠᠷᠢᠭᠰᠠᠭᠠᠷ ᠪᠠᠶᠢᠪᠠ᠃',
    id: 'yuan-retreat-1368',
    startYear: 1368,
    endYear: 1368,
    precision: 'year',
    sources: ['wiki-yuan', 'wiki-toghon-en', 'wiki-toghon-mn'],
  },
];
const SOURCES = {
  armouries: {
    name: 'ᠴᠢᠩᠭᠢᠰ ᠬᠠᠭᠠᠨ ᠤ ᠭᠡᠷ ᠪᠦᠯᠢ · ᠪᠷᠢᠲ᠋ᠠᠨᠢ ᠶᠢᠨ ᠬᠠᠭᠠᠨ ᠤ ᠵᠡᠪᠰᠡᠭ ᠦᠨ ᠮᠦᠽᠧᠢ',
    url: 'https://royalarmouries.org/objects-and-stories/stories/the-mongols/the-family-of-genghis-khan',
  },
  columbia: {
    name: 'ᠮᠣᠩᠭᠣᠯ ᠪᠠ ᠳᠡᠯᠡᠬᠡᠢ ᠶᠢᠨ ᠲᠡᠦᠬᠡ · ᠺᠣᠯᠤᠮᠪᠢᠶ᠎ᠠ ᠶᠢᠨ ᠶᠡᠬᠡ ᠰᠤᠷᠭᠠᠭᠤᠯᠢ',
    url: 'https://afe.easia.columbia.edu/mongols/index.htm',
  },
  cambridge: {
    name: 'ᠬᠤᠪᠢᠯᠠᠢ ᠶᠢᠨ ᠬᠠᠭᠠᠨᠴᠢᠯᠠᠯ · ᠺᠧᠮᠪᠷᠢᠵ ᠦᠨ ᠬᠢᠲᠠᠳ ᠤᠨ ᠲᠡᠦᠬᠡ',
    url: 'https://www.cambridge.org/core/books/abs/cambridge-history-of-china/reign-of-khubilai-khan/5A78D2CB4336B15FB090E0532672D3CA',
  },
  chabi: {
    name: 'ᠴᠠᠪᠢ ᠬᠠᠲᠤᠨ · ᠷᠣᠰᠰᠠᠪᠢ ᠶᠢᠨ ᠰᠤᠳᠤᠯᠤᠯ',
    url: 'https://www-1.gsb.columbia.edu/mongols/pop/khubilai/chabi_reading.htm',
  },
  met: {
    name: 'ᠬᠤᠪᠢᠯᠠᠢ ᠶᠢᠨ ᠳᠡᠯᠡᠬᠡᠢ · ᠮᠧᠲᠷᠣᠫᠣᠯᠢᠲ᠋ᠠᠨ ᠮᠦᠽᠧᠢ',
    url: 'https://www.metmuseum.org/exhibitions/listings/2010/khubilai-khan',
  },
  yuan1: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 1 ᠳᠦᠭᠡᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷001',
  },
  yuan115: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 115 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷115',
  },
  yuan18: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 18 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史_(四庫全書本)/卷018',
  },
  yuan22: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 22 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷022',
  },
  yuan31: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 31 ᠳᠦᠭᠡᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷031',
  },
  yuan38: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 38 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷038',
  },
  isdp: {
    name: 'ᠸᠠᠩ ᠬᠠᠨ ᠪᠠ ᠵᠠᠮᠤᠬ᠎ᠠ ᠶᠢᠨ ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠣᠯᠪᠤᠭ᠎ᠠ · ᠪᠡᠳᠡᠰᠺᠢ ᠶᠢᠨ ᠰᠤᠳᠤᠯᠤᠯ',
    url: 'https://www.isdp.eu/wp-content/uploads/publications/2013-bedeski-reinventing-human-security.pdf',
  },
  yuan3: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 3 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷003',
  },
  dunnell2023: {
    name: 'ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠡᠵᠡᠨᠲᠦ ᠭᠦᠷᠦᠨ ᠦ ᠲᠡᠦᠬᠡ · ᠺᠧᠮᠪᠷᠢᠵ ᠦᠨ ᠶᠡᠬᠡ ᠰᠤᠷᠭᠠᠭᠤᠯᠢ',
    url: 'https://api.pageplace.de/preview/DT0400.9781009301985_A49234927/preview-9781009301985_A49234927.pdf',
  },
  iranicaJoci: {
    name: 'ᠵᠦᠴᠢ · ᠢᠷᠠᠨᠢᠺᠠ ᠨᠡᠪᠲᠡᠷᠬᠡᠢ ᠲᠣᠯᠢ',
    url: 'https://www.iranicaonline.org/articles/joci/',
  },
  iranicaHulagu: {
    name: 'ᠬᠦᠯᠡᠭᠦ · ᠢᠷᠠᠨᠢᠺᠠ ᠨᠡᠪᠲᠡᠷᠬᠡᠢ ᠲᠣᠯᠢ',
    url: 'https://www.iranicaonline.org/articles/hulagu-khan/',
  },
  iranicaChinaIran: {
    name: 'ᠬᠢᠲᠠᠳ ᠪᠠ ᠢᠷᠠᠨ ᠤ ᠬᠠᠷᠢᠯᠴᠠᠭ᠎ᠠ · ᠢᠷᠠᠨᠢᠺᠠ ᠨᠡᠪᠲᠡᠷᠬᠡᠢ ᠲᠣᠯᠢ',
    url: 'https://www.iranicaonline.org/articles/chinese-iranian-iii/',
  },
  iranicaMongols: {
    name: 'ᠮᠣᠩᠭᠣᠯ · ᠢᠷᠠᠨᠢᠺᠠ ᠨᠡᠪᠲᠡᠷᠬᠡᠢ ᠲᠣᠯᠢ',
    url: 'https://www.iranicaonline.org/articles/mongols/',
  },
  shm48: {
    name: 'ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠨᠢᠭᠤᠴᠠ ᠲᠣᠪᠴᠢᠶᠠᠨ · 48',
    url: 'https://sourcebooks.web.fordham.edu/basis/The%20Secret%20History%20of%20the%20Mongols_%20A%20Mongolian%20Epic%20Chronicle%20of.pdf#page=34',
  },
  shm50: {
    name: 'ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠨᠢᠭᠤᠴᠠ ᠲᠣᠪᠴᠢᠶᠠᠨ · 50',
    url: 'https://sourcebooks.web.fordham.edu/basis/The%20Secret%20History%20of%20the%20Mongols_%20A%20Mongolian%20Epic%20Chronicle%20of.pdf#page=34',
  },
  shm52: {
    name: 'ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠨᠢᠭᠤᠴᠠ ᠲᠣᠪᠴᠢᠶᠠᠨ · 52',
    url: 'https://sourcebooks.web.fordham.edu/basis/The%20Secret%20History%20of%20the%20Mongols_%20A%20Mongolian%20Epic%20Chronicle%20of.pdf#page=34',
  },
  mongoltoliKhabul: {
    name: 'ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ · ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠲᠡᠦᠬᠡ ᠶᠢᠨ ᠲᠠᠶᠢᠯᠪᠤᠷᠢ ᠲᠣᠯᠢ',
    url: 'https://mongoltoli.mn/history/h/466',
  },
  mongoltoliYesugei: {
    name: 'ᠶᠡᠰᠦᠭᠡᠢ ᠪᠠᠭᠠᠲᠤᠷ · ᠮᠣᠩᠭᠣᠯ ᠤᠨ ᠲᠡᠦᠬᠡ ᠶᠢᠨ ᠲᠠᠶᠢᠯᠪᠤᠷᠢ ᠲᠣᠯᠢ',
    url: 'https://www.mongoltoli.mn/history/h/431',
  },
  yuan114: {
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 114 ᠳᠦᠭᠡᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/元史/卷114',
  },
  mingTaizu57: {
    name: 'ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠲᠠᠢᠵᠦ ᠶᠢᠨ ᠦᠨᠡᠨ ᠲᠡᠮᠳᠡᠭᠯᠡᠯ · 57 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/大明太祖高皇帝實錄/卷057',
  },
  ming327: {
    name: 'ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 327 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/明史/卷327',
  },
  newYuan26: {
    name: 'ᠰᠢᠨ᠎ᠡ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 26 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/新元史/卷026',
  },
  okada1994: {
    name: 'ᠳᠠᠶᠠᠨ ᠬᠠᠭᠠᠨ ᠤ ᠤᠳᠤᠮ ᠤᠨ ᠰᠤᠳᠤᠯᠭ᠎ᠠ · 1994',
    url: 'https://www.persee.fr/doc/befeo_0336-1519_1994_num_81_1_2245?pageId=T1_53',
  },
};
const RESEARCH_GAPS = [
  {
    id: 'toghon-third-generation-unresolved',
    kind: 'research-gap',
    isPerson: false,
    anchor: 'maidarbal',
    generationFromToghon: 3,
    pos: [1460, 2700],
    title: 'ᠭᠤᠷᠪᠠᠳᠤᠭᠠᠷ ᠦᠶ᠎ᠡ',
    detailTitle: 'ᠭᠤᠷᠪᠠᠳᠤᠭᠠᠷ ᠦᠶ᠎ᠡ᠄ ᠲᠣᠳᠣᠷᠬᠠᠢ ᠪᠤᠰᠤ',
    shortLabel: 'ᠲᠣᠳᠣᠷᠬᠠᠢ ᠪᠤᠰᠤ',
    legendLabel: 'ᠲᠣᠳᠣᠷᠬᠠᠢ ᠪᠤᠰᠤ ᠦᠶ᠎ᠡ',
    summary: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠤᠨ ᠦᠷ᠎ᠡ ᠬᠡᠦᠬᠡᠳ ᠦᠨ ᠲᠤᠬᠠᠢ ᠰᠤᠷᠪᠤᠯᠵᠢ ᠶᠢ ᠴᠢᠮᠪᠠᠢᠷᠠᠭᠤᠯᠤᠨ ᠰᠤᠳᠤᠯᠬᠤ ᠬᠡᠷᠡᠭᠲᠡᠢ᠃',
    notes: [
      'ᠲᠥᠭᠦᠰᠲᠡᠮᠦᠷ ᠢ ᠨᠢᠭᠡ ᠰᠤᠷᠪᠤᠯᠵᠢ ᠳᠤ ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠶᠢᠨ ᠬᠥᠪᠡᠭᠦᠨ᠂ ᠨᠥᠭᠥᠭᠡ ᠳᠦ ᠳᠡᠭᠦᠦ ᠨᠢ ᠭᠡᠵᠦ ᠪᠢᠴᠢᠵᠡᠢ᠃',
    ],
    sources: ['mingTaizu57', 'ming327', 'newYuan26', 'okada1994'],
  },
];

// Recorded early Northern Yuan succession and external Ming contacts.
Object.assign(SOURCES, {
  mingTaizu53: {
    name: 'ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠲᠠᠢᠵᠦ ᠶᠢᠨ ᠦᠨᠡᠨ ᠲᠡᠮᠳᠡᠭᠯᠡᠯ · 53 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/大明太祖高皇帝實錄/卷053',
  },
  mingTaizu57: {
    name: 'ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠲᠠᠢᠵᠦ ᠶᠢᠨ ᠦᠨᠡᠨ ᠲᠡᠮᠳᠡᠭᠯᠡᠯ · 57 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/大明太祖高皇帝實錄/卷057',
  },
  ming327: {
    name: 'ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 327 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/明史/卷327',
  },
  okada1994: {
    name: 'ᠳᠠᠶᠠᠨ ᠬᠠᠭᠠᠨ ᠤ ᠤᠳᠤᠮ ᠤᠨ ᠰᠤᠳᠤᠯᠭ᠎ᠠ · 1994',
    url: 'https://www.persee.fr/doc/befeo_0336-1519_1994_num_81_1_2245?pageId=T1_53',
  },
  newYuan26: {
    name: 'ᠰᠢᠨ᠎ᠡ ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ ᠤᠨ ᠰᠤᠳᠤᠷ · 26 ᠳᠤᠭᠠᠷ ᠳᠡᠪᠲᠡᠷ',
    url: 'https://zh.wikisource.org/wiki/新元史/卷026',
  },
});
Object.assign(PEOPLE, {
  hongwu: {
    name: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ',
    alias: 'ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠬᠠᠭᠠᠨ',
    years: '14 ᠳᠦᠭᠡᠷ ᠵᠠᠭᠤᠨ',
    era: 'ᠮᠢᠩ ᠤᠯᠤᠰ',
    summary: '1370 ᠣᠨ ᠳᠤ ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠳᠤ ᠪᠢᠴᠢᠭ ᠢᠯᠡᠭᠡᠵᠡᠢ᠃ 1374 ᠣᠨ ᠳᠤ ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠢ ᠤᠮᠠᠷ᠎ᠠ ᠪᠤᠴᠠᠭᠠᠵᠠᠢ᠃',
    note: 'ᠡᠨᠳᠡ ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠠᠷᠢᠯᠴᠠᠭ᠎ᠠ ᠶᠢ ᠲᠠᠶᠢᠯᠪᠤᠷᠢᠯᠠᠬᠤ ᠪᠠᠷ ᠣᠷᠣᠭᠤᠯᠪᠠ᠃',
    sources: ['mingTaizu53', 'mingTaizu57', 'ming327', 'wiki-hongwu-en', 'wiki-hongwu-mn'],
    externalContext: true,
    lineageRole: 'outside-borjigin',
    views: ['power'],
    pos: [1780, 2470],
    power: [1320, 2470],
    positionNote:
      'Place with the Ming political context alongside the documented correspondence links.',
  },
});
EDGES.push(
  ...[
    {
      id: 'toghon-ayushiridara-succession-1370',
      from: 'toghon',
      to: 'ayushiridara',
      type: 'succession',
      label: '1370 · ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠪᠠ',
      sources: ['okada1994', 'newYuan26', 'wiki-ayushiridara-en', 'wiki-ayushiridara-mn'],
      sourceLocators: {
        okada1994: 'p. 53',
        newYuan26: '昭宗, 至正三十年夏四月',
      },
      certainty: 'documented',
      period: {
        fromYear: 1370,
        toYear: 1370,
        precision: 'year',
        semantics: 'accession after Toghon Temur’s death',
      },
      note: 'Political succession and parentage use separate edge types.',
    },
    {
      id: 'hongwu-ayushiridara-contact-1370',
      from: 'hongwu',
      to: 'ayushiridara',
      type: 'contact',
      label: '1370 · ᠪᠢᠴᠢᠭ ᠢᠯᠡᠭᠡᠪᠡ',
      sources: ['mingTaizu57'],
      sourceLocators: {
        mingTaizu57: '洪武三年冬十月, two letters to 愛猷識里達臘',
      },
      certainty: 'documented',
      period: {
        fromYear: 1370,
        toYear: 1370,
        precision: 'year',
        originalDate: '洪武三年冬十月',
        semantics: 'recorded letters sent by Hongwu',
      },
      note: 'Official communication includes demands for submission; classify the documented letters as contact.',
    },
    {
      id: 'hongwu-maidarbal-contact-1370-1374',
      from: 'hongwu',
      to: 'maidarbal',
      type: 'contact',
      label: '1370 / 1374 · ᠲᠡᠮᠳᠡᠭᠯᠡᠭᠳᠡᠭᠰᠡᠨ ᠬᠠᠷᠢᠯᠴᠠᠭ᠎ᠠ',
      sources: ['mingTaizu53', 'ming327'],
      sourceLocators: {
        mingTaizu53: '洪武三年六月乙亥, audience and title grant',
        ming327: '洪武三年 and 洪武七年秋',
      },
      certainty: 'documented',
      period: {
        fromYear: 1370,
        toYear: 1374,
        years: [1370, 1374],
        precision: 'selected dated episodes',
        semantics: '1370 court reception and title after capture; 1374 dispatch north.',
      },
      note: 'Maidarbal was a captive; Hongwu received him at court and later sent him north.',
    },
  ],
);
EVENTS.push(
  ...[
    {
      id: 'ayushiridara-accession-1370',
      date: '1370',
      title: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠬᠠᠭᠠᠨ ᠰᠠᠭᠤᠪᠠ',
      people: ['toghon', 'ayushiridara'],
      text: 'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ ᠢ ᠨᠠᠰᠤ ᠪᠠᠷᠠᠭᠰᠠᠨ ᠤ ᠳᠠᠷᠠᠭ᠎ᠠ ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠪᠠ᠃',
      sources: ['okada1994', 'newYuan26', 'wiki-ayushiridara-en', 'wiki-ayushiridara-mn'],
      graphMode: 'power',
      focusRelations: true,
    },
    {
      id: 'maidarbal-capture-1370',
      date: '1370',
      title: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠣᠯᠵᠠᠯᠠᠭᠳᠠᠪᠠ',
      people: ['maidarbal'],
      text: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠮᠢᠩ ᠤᠯᠤᠰ ᠤᠨ ᠴᠡᠷᠢᠭ ᠲᠦ ᠣᠯᠵᠠᠯᠠᠭᠳᠠᠪᠠ᠃',
      sources: ['mingTaizu53', 'ming327', 'wiki-maidarbal-en', 'wiki-ayushiridara-mn'],
      graphMode: 'power',
      focusRelations: false,
    },
    {
      id: 'hongwu-ayushiridara-letter-1370',
      date: '1370',
      title: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ ᠪᠢᠴᠢᠭ ᠢᠯᠡᠭᠡᠪᠡ',
      people: ['hongwu', 'ayushiridara'],
      text: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ ᠳᠤ ᠪᠢᠴᠢᠭ ᠢᠯᠡᠭᠡᠪᠡ᠃ ᠪᠢᠴᠢᠭ ᠲᠦ ᠲᠡᠭᠦᠨ ᠦ ᠬᠥᠪᠡᠭᠦᠨ ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠤᠨ ᠲᠤᠬᠠᠢ ᠲᠡᠮᠳᠡᠭᠯᠡᠵᠡᠢ᠃',
      sources: ['mingTaizu57'],
      graphMode: 'power',
      focusRelations: true,
    },
    {
      id: 'maidarbal-return-1374',
      date: '1374',
      title: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠢ ᠤᠮᠠᠷ᠎ᠠ ᠪᠤᠴᠠᠭᠠᠪᠠ',
      people: ['hongwu', 'maidarbal'],
      text: '1374 ᠣᠨ ᠤ ᠨᠠᠮᠤᠷ ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ ᠢ ᠤᠮᠠᠷ᠎ᠠ ᠪᠤᠴᠠᠭᠠᠪᠠ᠃',
      sources: ['ming327', 'wiki-maidarbal-en', 'wiki-ayushiridara-mn'],
      graphMode: 'power',
      focusRelations: true,
    },
  ],
);
const RELATION_UI = {
  politicalRelationsHint: 'ᠤᠷᠤᠭ ᠲᠥᠷᠥᠯ ᠦᠨ ᠵᠢᠷᠤᠭ ᠠᠴᠠ ᠲᠤᠰ ᠬᠦᠮᠦᠨ ᠦ ᠬᠣᠯᠪᠤᠭ᠎ᠠ ᠶᠢ ᠦᠵᠡᠭᠡᠷᠡᠢ᠃',
  familyTitle: 'ᠡᠴᠢᠭᠡ ᠡᠬᠡ ᠪᠠ ᠦᠷ᠎ᠡ ᠬᠡᠦᠬᠡᠳ · ᠭᠡᠷᠯᠡᠯᠲᠡ',
  powerTitle: 'ᠬᠠᠭᠠᠨ ᠰᠢᠷᠡᠭᠡ ᠶᠢᠨ ᠵᠠᠯᠭᠠᠮᠵᠢᠯᠠᠯ · ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠶᠢᠨ ᠬᠣᠯᠪᠤᠭ᠎ᠠ',
  sourceHint: 'ᠬᠣᠯᠪᠤᠭᠳᠠᠬᠤ ᠰᠤᠷᠪᠤᠯᠵᠢ ᠶᠢ ᠦᠵᠡᠭᠡᠷᠡᠢ᠃',
  viewFamilyRelationships: 'ᠤᠷᠤᠭ ᠲᠥᠷᠥᠯ ᠦᠨ ᠬᠣᠯᠪᠤᠭ᠎ᠠ ᠶᠢ ᠦᠵᠡᠬᠦ',
  contact: 'ᠲᠡᠮᠳᠡᠭᠯᠡᠭᠳᠡᠭᠰᠡᠨ ᠬᠠᠷᠢᠯᠴᠠᠭ᠎ᠠ',
  contactExplanation: 'ᠰᠤᠷᠪᠤᠯᠵᠢ ᠳᠤ ᠲᠡᠮᠳᠡᠭᠯᠡᠭᠳᠡᠭᠰᠡᠨ ᠬᠠᠷᠢᠯᠴᠠᠭ᠎ᠠ᠃',
  externalContext: 'ᠤᠯᠤᠰ ᠲᠥᠷᠥ ᠶᠢᠨ ᠣᠷᠴᠢᠨ',
};

// Wikipedia source revisions.
Object.assign(SOURCES, {
  'wiki-mongol-empire': {
    kind: 'wikipedia',
    title: 'ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ',
    name: 'ᠶᠡᠬᠡ ᠮᠣᠩᠭᠣᠯ ᠤᠯᠤᠰ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1378170057',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Mongol_Empire',
    pageId: 240146,
    revisionId: 1378170057,
    originalTitle: 'Mongol Empire',
    language: 'en',
    retrievedAt: '2026-10-07T06:16:15.581Z',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Mongol_Empire?action=history',
  },
  'wiki-genghis-khan': {
    kind: 'wikipedia',
    title: 'ᠲᠡᠮᠦᠵᠢᠨ · ᠠᠩᠭᠯᠢ',
    name: 'ᠲᠡᠮᠦᠵᠢᠨ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1379007070',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Genghis_Khan',
    pageId: 17414699,
    revisionId: 1379007070,
    originalTitle: 'Genghis Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Genghis_Khan?action=history',
  },
  'wiki-yuan': {
    kind: 'wikipedia',
    title: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    name: 'ᠶᠤᠸᠠᠨ ᠤᠯᠤᠰ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1377782070',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Yuan_dynasty',
    pageId: 19606306,
    revisionId: 1377782070,
    originalTitle: 'Yuan dynasty',
    language: 'en',
    retrievedAt: '2026-10-07T06:16:15.582Z',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Yuan_dynasty?action=history',
  },
  'wiki-toregene': {
    kind: 'wikipedia',
    title: 'ᠳᠥᠷᠡᠭᠡᠨᠡ · ᠠᠩᠭᠯᠢ',
    name: 'ᠳᠥᠷᠡᠭᠡᠨᠡ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1377001136',
    canonicalUrl: 'https://en.wikipedia.org/wiki/T%C3%B6regene_Khatun',
    pageId: 795963,
    revisionId: 1377001136,
    originalTitle: 'Töregene Khatun',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/T%C3%B6regene_Khatun?action=history',
  },
  'wiki-jochi-en': {
    kind: 'wikipedia',
    title: 'ᠵᠦᠴᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠵᠦᠴᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1372163395',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Jochi',
    pageId: 745324,
    revisionId: 1372163395,
    originalTitle: 'Jochi',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Jochi?action=history',
  },
  'wiki-yesugei-en': {
    kind: 'wikipedia',
    title: 'ᠶᠢᠰᠦᠭᠡᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠶᠢᠰᠦᠭᠡᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1373053559',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Yesugei',
    pageId: 36297604,
    revisionId: 1373053559,
    originalTitle: 'Yesugei',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Yesugei?action=history',
  },
  'wiki-yesugei-mn': {
    kind: 'wikipedia',
    title: 'ᠶᠢᠰᠦᠭᠡᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠶᠢᠰᠦᠭᠡᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=840713',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%95%D1%81%D2%AF%D1%85%D1%8D%D0%B9_%D0%B1%D0%B0%D0%B0%D1%82%D0%B0%D1%80',
    pageId: 10423,
    revisionId: 840713,
    originalTitle: 'Есүхэй баатар',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%95%D1%81%D2%AF%D1%85%D1%8D%D0%B9_%D0%B1%D0%B0%D0%B0%D1%82%D0%B0%D1%80?action=history',
  },
  'wiki-hoelun-en': {
    kind: 'wikipedia',
    title: 'ᠥᠭᠡᠯᠦᠨ · ᠠᠩᠭᠯᠢ',
    name: 'ᠥᠭᠡᠯᠦᠨ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1369928359',
    canonicalUrl: 'https://en.wikipedia.org/wiki/H%C3%B6%27el%C3%BCn',
    pageId: 1420929,
    revisionId: 1369928359,
    originalTitle: "Hö'elün",
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/H%C3%B6%27el%C3%BCn?action=history',
  },
  'wiki-hoelun-mn': {
    kind: 'wikipedia',
    title: 'ᠥᠭᠡᠯᠦᠨ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠥᠭᠡᠯᠦᠨ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=850086',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D3%A8%D1%8D%D0%BB%D2%AF%D0%BD',
    pageId: 9955,
    revisionId: 850086,
    originalTitle: 'Өэлүн',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://mn.wikipedia.org/wiki/%D3%A8%D1%8D%D0%BB%D2%AF%D0%BD?action=history',
  },
  'wiki-temujin-mn': {
    kind: 'wikipedia',
    title: 'ᠲᠡᠮᠦᠵᠢᠨ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠲᠡᠮᠦᠵᠢᠨ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=872728',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A7%D0%B8%D0%BD%D0%B3%D0%B8%D1%81_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 1264,
    revisionId: 872728,
    originalTitle: 'Чингис хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A7%D0%B8%D0%BD%D0%B3%D0%B8%D1%81_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-borte-en': {
    kind: 'wikipedia',
    title: 'ᠪᠥᠷᠲᠡ · ᠠᠩᠭᠯᠢ',
    name: 'ᠪᠥᠷᠲᠡ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1371041540',
    canonicalUrl: 'https://en.wikipedia.org/wiki/B%C3%B6rte',
    pageId: 489477,
    revisionId: 1371041540,
    originalTitle: 'Börte',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/B%C3%B6rte?action=history',
  },
  'wiki-borte-mn': {
    kind: 'wikipedia',
    title: 'ᠪᠥᠷᠲᠡ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠪᠥᠷᠲᠡ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=848319',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%91%D3%A9%D1%80%D1%82%D1%8D_%D2%AF%D0%B6%D0%B8%D0%BD',
    pageId: 10426,
    revisionId: 848319,
    originalTitle: 'Бөртэ үжин',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%91%D3%A9%D1%80%D1%82%D1%8D_%D2%AF%D0%B6%D0%B8%D0%BD?action=history',
  },
  'wiki-jochi-mn': {
    kind: 'wikipedia',
    title: 'ᠵᠦᠴᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠵᠦᠴᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=857321',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%97%D2%AF%D1%87%D0%B8',
    pageId: 20656,
    revisionId: 857321,
    originalTitle: 'Зүчи',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://mn.wikipedia.org/wiki/%D0%97%D2%AF%D1%87%D0%B8?action=history',
  },
  'wiki-chagatai-en': {
    kind: 'wikipedia',
    title: 'ᠴᠠᠭᠠᠳᠠᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠴᠠᠭᠠᠳᠠᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1369183605',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Chagatai_Khan',
    pageId: 795693,
    revisionId: 1369183605,
    originalTitle: 'Chagatai Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Chagatai_Khan?action=history',
  },
  'wiki-chagatai-mn': {
    kind: 'wikipedia',
    title: 'ᠴᠠᠭᠠᠳᠠᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠴᠠᠭᠠᠳᠠᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=841483',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%A6%D0%B0%D0%B3%D0%B0%D0%B4%D0%B0%D0%B9',
    pageId: 21357,
    revisionId: 841483,
    originalTitle: 'Цагадай',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A6%D0%B0%D0%B3%D0%B0%D0%B4%D0%B0%D0%B9?action=history',
  },
  'wiki-ogedei-en': {
    kind: 'wikipedia',
    title: 'ᠥᠭᠡᠳᠡᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠥᠭᠡᠳᠡᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1377651581',
    canonicalUrl: 'https://en.wikipedia.org/wiki/%C3%96gedei_Khan',
    pageId: 739857,
    revisionId: 1377651581,
    originalTitle: 'Ögedei Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/%C3%96gedei_Khan?action=history',
  },
  'wiki-ogedei-mn': {
    kind: 'wikipedia',
    title: 'ᠥᠭᠡᠳᠡᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠥᠭᠡᠳᠡᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=870229',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D3%A8%D0%B3%D1%8D%D0%B4%D1%8D%D0%B9_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 1914,
    revisionId: 870229,
    originalTitle: 'Өгэдэй хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D3%A8%D0%B3%D1%8D%D0%B4%D1%8D%D0%B9_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-toregene-mn': {
    kind: 'wikipedia',
    title: 'ᠳᠥᠷᠡᠭᠡᠨᠡ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠳᠥᠷᠡᠭᠡᠨᠡ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=865641',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%94%D3%A9%D1%80%D0%B3%D3%A9%D0%BD%D1%8D',
    pageId: 23514,
    revisionId: 865641,
    originalTitle: 'Дөргөнэ',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%94%D3%A9%D1%80%D0%B3%D3%A9%D0%BD%D1%8D?action=history',
  },
  'wiki-tolui-en': {
    kind: 'wikipedia',
    title: 'ᠲᠣᠯᠤᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠲᠣᠯᠤᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1378112943',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Tolui',
    pageId: 744553,
    revisionId: 1378112943,
    originalTitle: 'Tolui',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Tolui?action=history',
  },
  'wiki-tolui-mn': {
    kind: 'wikipedia',
    title: 'ᠲᠣᠯᠤᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠲᠣᠯᠤᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=841755',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%A2%D1%83%D0%BB%D1%83%D0%B9',
    pageId: 10432,
    revisionId: 841755,
    originalTitle: 'Тулуй',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://mn.wikipedia.org/wiki/%D0%A2%D1%83%D0%BB%D1%83%D0%B9?action=history',
  },
  'wiki-sorghaghtani-en': {
    kind: 'wikipedia',
    title: 'ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1368287362',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Sorghaghtani_Beki',
    pageId: 1554826,
    revisionId: 1368287362,
    originalTitle: 'Sorghaghtani Beki',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Sorghaghtani_Beki?action=history',
  },
  'wiki-sorghaghtani-mn': {
    kind: 'wikipedia',
    title: 'ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠰᠣᠷᠬᠤᠭᠲᠠᠨᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=869703',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A1%D0%BE%D1%80%D1%85%D0%B0%D0%B3%D1%82%D0%B0%D0%BD%D0%B8_%D0%91%D1%8D%D1%85%D0%B8',
    pageId: 7583,
    revisionId: 869703,
    originalTitle: 'Сорхагтани Бэхи',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A1%D0%BE%D1%80%D1%85%D0%B0%D0%B3%D1%82%D0%B0%D0%BD%D0%B8_%D0%91%D1%8D%D1%85%D0%B8?action=history',
  },
  'wiki-guyuk-en': {
    kind: 'wikipedia',
    title: 'ᠭᠦᠶᠦᠭ · ᠠᠩᠭᠯᠢ',
    name: 'ᠭᠦᠶᠦᠭ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1376532753',
    canonicalUrl: 'https://en.wikipedia.org/wiki/G%C3%BCy%C3%BCk_Khan',
    pageId: 742592,
    revisionId: 1376532753,
    originalTitle: 'Güyük Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/G%C3%BCy%C3%BCk_Khan?action=history',
  },
  'wiki-guyuk-mn': {
    kind: 'wikipedia',
    title: 'ᠭᠦᠶᠦᠭ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠭᠦᠶᠦᠭ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=859035',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%93%D2%AF%D1%8E%D0%B3_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 8765,
    revisionId: 859035,
    originalTitle: 'Гүюг хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%93%D2%AF%D1%8E%D0%B3_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-mongke-en': {
    kind: 'wikipedia',
    title: 'ᠮᠥᠩᠬᠡ · ᠠᠩᠭᠯᠢ',
    name: 'ᠮᠥᠩᠬᠡ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1375554835',
    canonicalUrl: 'https://en.wikipedia.org/wiki/M%C3%B6ngke_Khan',
    pageId: 742605,
    revisionId: 1375554835,
    originalTitle: 'Möngke Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/M%C3%B6ngke_Khan?action=history',
  },
  'wiki-mongke-mn': {
    kind: 'wikipedia',
    title: 'ᠮᠥᠩᠬᠡ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠮᠥᠩᠬᠡ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=840324',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%9C%D3%A9%D0%BD%D1%85_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 5003,
    revisionId: 840324,
    originalTitle: 'Мөнх хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%9C%D3%A9%D0%BD%D1%85_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-kublai-en': {
    kind: 'wikipedia',
    title: 'ᠬᠤᠪᠢᠯᠠᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠬᠤᠪᠢᠯᠠᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1376691119',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Kublai_Khan',
    pageId: 20754760,
    revisionId: 1376691119,
    originalTitle: 'Kublai Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Kublai_Khan?action=history',
  },
  'wiki-kublai-mn': {
    kind: 'wikipedia',
    title: 'ᠬᠤᠪᠢᠯᠠᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠬᠤᠪᠢᠯᠠᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=871885',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D1%83%D0%B1%D0%B8%D0%BB%D0%B0%D0%B9_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 1267,
    revisionId: 871885,
    originalTitle: 'Хубилай хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D1%83%D0%B1%D0%B8%D0%BB%D0%B0%D0%B9_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-chabi-en': {
    kind: 'wikipedia',
    title: 'ᠴᠠᠪᠢ · ᠠᠩᠭᠯᠢ',
    name: 'ᠴᠠᠪᠢ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1367465775',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Chabi',
    pageId: 24967743,
    revisionId: 1367465775,
    originalTitle: 'Chabi',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Chabi?action=history',
  },
  'wiki-chabi-mn': {
    kind: 'wikipedia',
    title: 'ᠴᠠᠪᠢ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠴᠠᠪᠢ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=855753',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A7%D0%B0%D0%B1%D0%B8_%D1%85%D0%B0%D1%82%D0%B0%D0%BD',
    pageId: 35282,
    revisionId: 855753,
    originalTitle: 'Чаби хатан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A7%D0%B0%D0%B1%D0%B8_%D1%85%D0%B0%D1%82%D0%B0%D0%BD?action=history',
  },
  'wiki-ariq-en': {
    kind: 'wikipedia',
    title: 'ᠠᠷᠢᠭᠪᠥᠬᠡ · ᠠᠩᠭᠯᠢ',
    name: 'ᠠᠷᠢᠭᠪᠥᠬᠡ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1367480551',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Ariq_B%C3%B6ke',
    pageId: 1489230,
    revisionId: 1367480551,
    originalTitle: 'Ariq Böke',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Ariq_B%C3%B6ke?action=history',
  },
  'wiki-ariq-mn': {
    kind: 'wikipedia',
    title: 'ᠠᠷᠢᠭᠪᠥᠬᠡ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠠᠷᠢᠭᠪᠥᠬᠡ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=858714',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%90%D1%80%D0%B8%D0%B3%D0%B1%D1%83%D1%85%D0%B0_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 18471,
    revisionId: 858714,
    originalTitle: 'Аригбуха хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%90%D1%80%D0%B8%D0%B3%D0%B1%D1%83%D1%85%D0%B0_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-zhenjin-en': {
    kind: 'wikipedia',
    title: 'ᠴᠢᠩᠭᠢᠮ · ᠠᠩᠭᠯᠢ',
    name: 'ᠴᠢᠩᠭᠢᠮ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1365294840',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Zhenjin',
    pageId: 19127910,
    revisionId: 1365294840,
    originalTitle: 'Zhenjin',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Zhenjin?action=history',
  },
  'wiki-zhenjin-mn': {
    kind: 'wikipedia',
    title: 'ᠴᠢᠩᠭᠢᠮ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠴᠢᠩᠭᠢᠮ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=859178',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%A7%D0%B8%D0%BD%D0%B3%D0%B8%D0%BC',
    pageId: 35445,
    revisionId: 859178,
    originalTitle: 'Чингим',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A7%D0%B8%D0%BD%D0%B3%D0%B8%D0%BC?action=history',
  },
  'wiki-temur-en': {
    kind: 'wikipedia',
    title: 'ᠲᠡᠮᠦᠷ · ᠠᠩᠭᠯᠢ',
    name: 'ᠲᠡᠮᠦᠷ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1367748674',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Tem%C3%BCr_Khan',
    pageId: 1088738,
    revisionId: 1367748674,
    originalTitle: 'Temür Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Tem%C3%BCr_Khan?action=history',
  },
  'wiki-temur-mn': {
    kind: 'wikipedia',
    title: 'ᠲᠡᠮᠦᠷ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠲᠡᠮᠦᠷ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=840363',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D3%A9%D0%BC%D3%A9%D1%80_%D3%A8%D0%BB%D0%B7%D0%B8%D0%B9%D1%82_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 20555,
    revisionId: 840363,
    originalTitle: 'Төмөр Өлзийт хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D3%A9%D0%BC%D3%A9%D1%80_%D3%A8%D0%BB%D0%B7%D0%B8%D0%B9%D1%82_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-darmabala-en': {
    kind: 'wikipedia',
    title: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ · ᠠᠩᠭᠯᠢ',
    name: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1365294850',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Darmabala',
    pageId: 66580420,
    revisionId: 1365294850,
    originalTitle: 'Darmabala',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Darmabala?action=history',
  },
  'wiki-darmabala-mn': {
    kind: 'wikipedia',
    title: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠳᠠᠷᠮᠠᠪᠠᠯᠠ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=849295',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%94%D0%B0%D1%80%D0%BC%D0%B0%D0%B1%D0%B0%D0%BB%D0%B0',
    pageId: 35431,
    revisionId: 849295,
    originalTitle: 'Дармабала',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%94%D0%B0%D1%80%D0%BC%D0%B0%D0%B1%D0%B0%D0%BB%D0%B0?action=history',
  },
  'wiki-qaishan-en': {
    kind: 'wikipedia',
    title: 'ᠬᠠᠢᠰᠠᠨ · ᠠᠩᠭᠯᠢ',
    name: 'ᠬᠠᠢᠰᠠᠨ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1367863120',
    canonicalUrl: 'https://en.wikipedia.org/wiki/K%C3%BCl%C3%BCg_Khan',
    pageId: 1088731,
    revisionId: 1367863120,
    originalTitle: 'Külüg Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/K%C3%BCl%C3%BCg_Khan?action=history',
  },
  'wiki-qaishan-mn': {
    kind: 'wikipedia',
    title: 'ᠬᠠᠢᠰᠠᠨ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠬᠠᠢᠰᠠᠨ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=840483',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D0%B0%D0%B9%D1%81%D0%B0%D0%BD_%D1%85%D2%AF%D0%BB%D1%8D%D0%B3_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 24268,
    revisionId: 840483,
    originalTitle: 'Хайсан хүлэг хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D0%B0%D0%B9%D1%81%D0%B0%D0%BD_%D1%85%D2%AF%D0%BB%D1%8D%D0%B3_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-kusala-en': {
    kind: 'wikipedia',
    title: 'ᠬᠦᠰᠡᠯᠡ · ᠠᠩᠭᠯᠢ',
    name: 'ᠬᠦᠰᠡᠯᠡ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1366202242',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Khutughtu_Khan_Kusala',
    pageId: 1086606,
    revisionId: 1366202242,
    originalTitle: 'Khutughtu Khan Kusala',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Khutughtu_Khan_Kusala?action=history',
  },
  'wiki-kusala-mn': {
    kind: 'wikipedia',
    title: 'ᠬᠦᠰᠡᠯᠡ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠬᠦᠰᠡᠯᠡ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=869835',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D2%AF%D1%81%D0%BB%D1%8D%D0%BD_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 24312,
    revisionId: 869835,
    originalTitle: 'Хүслэн хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D2%AF%D1%81%D0%BB%D1%8D%D0%BD_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-toghon-en': {
    kind: 'wikipedia',
    title: 'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ · ᠠᠩᠭᠯᠢ',
    name: 'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1373355982',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Toghon_Tem%C3%BCr',
    pageId: 1080647,
    revisionId: 1373355982,
    originalTitle: 'Toghon Temür',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Toghon_Tem%C3%BCr?action=history',
  },
  'wiki-toghon-mn': {
    kind: 'wikipedia',
    title: 'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠲᠣᠭᠣᠨᠲᠡᠮᠦᠷ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=869849',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D0%BE%D0%B3%D0%BE%D0%BE%D0%BD%D1%82%D3%A9%D0%BC%D3%A9%D1%80_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 17447,
    revisionId: 869849,
    originalTitle: 'Тогоонтөмөр хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D0%BE%D0%B3%D0%BE%D0%BE%D0%BD%D1%82%D3%A9%D0%BC%D3%A9%D1%80_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-toghrul-en': {
    kind: 'wikipedia',
    title: 'ᠲᠣᠭᠣᠷᠢᠯ · ᠠᠩᠭᠯᠢ',
    name: 'ᠲᠣᠭᠣᠷᠢᠯ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1376378630',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Toghrul',
    pageId: 1671834,
    revisionId: 1376378630,
    originalTitle: 'Toghrul',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Toghrul?action=history',
  },
  'wiki-toghrul-mn': {
    kind: 'wikipedia',
    title: 'ᠲᠣᠭᠣᠷᠢᠯ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠲᠣᠭᠣᠷᠢᠯ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=840681',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BE%D1%80%D0%B8%D0%BB_%D1%85%D0%B0%D0%BD',
    pageId: 10230,
    revisionId: 840681,
    originalTitle: 'Тоорил хан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D0%BE%D0%BE%D1%80%D0%B8%D0%BB_%D1%85%D0%B0%D0%BD?action=history',
  },
  'wiki-jamukha-en': {
    kind: 'wikipedia',
    title: 'ᠵᠠᠮᠤᠬ᠎ᠠ · ᠠᠩᠭᠯᠢ',
    name: 'ᠵᠠᠮᠤᠬ᠎ᠠ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1368294424',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Jamukha',
    pageId: 1998565,
    revisionId: 1368294424,
    originalTitle: 'Jamukha',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Jamukha?action=history',
  },
  'wiki-jamukha-mn': {
    kind: 'wikipedia',
    title: 'ᠵᠠᠮᠤᠬ᠎ᠠ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠵᠠᠮᠤᠬ᠎ᠠ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=832521',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%96%D0%B0%D0%BC%D1%83%D1%85%D0%B0',
    pageId: 21406,
    revisionId: 832521,
    originalTitle: 'Жамуха',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%96%D0%B0%D0%BC%D1%83%D1%85%D0%B0?action=history',
  },
  'wiki-batu-en': {
    kind: 'wikipedia',
    title: 'ᠪᠠᠲᠤ · ᠠᠩᠭᠯᠢ',
    name: 'ᠪᠠᠲᠤ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1370297553',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Batu_Khan',
    pageId: 188698,
    revisionId: 1370297553,
    originalTitle: 'Batu Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Batu_Khan?action=history',
  },
  'wiki-batu-mn': {
    kind: 'wikipedia',
    title: 'ᠪᠠᠲᠤ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠪᠠᠲᠤ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=865006',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%91%D0%B0%D1%82_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 8180,
    revisionId: 865006,
    originalTitle: 'Бат хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%91%D0%B0%D1%82_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-hulegu-en': {
    kind: 'wikipedia',
    title: 'ᠬᠦᠯᠡᠭᠦ · ᠠᠩᠭᠯᠢ',
    name: 'ᠬᠦᠯᠡᠭᠦ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1368839446',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Hulegu_Khan',
    pageId: 354356,
    revisionId: 1368839446,
    originalTitle: 'Hulegu Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Hulegu_Khan?action=history',
  },
  'wiki-hulegu-mn': {
    kind: 'wikipedia',
    title: 'ᠬᠦᠯᠡᠭᠦ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠬᠦᠯᠡᠭᠦ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=860168',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%A5%D2%AF%D0%BB%D1%8D%D0%B3%D2%AF',
    pageId: 8245,
    revisionId: 860168,
    originalTitle: 'Хүлэгү',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D2%AF%D0%BB%D1%8D%D0%B3%D2%AF?action=history',
  },
  'wiki-berke-en': {
    kind: 'wikipedia',
    title: 'ᠪᠡᠷᠬᠡ · ᠠᠩᠭᠯᠢ',
    name: 'ᠪᠡᠷᠬᠡ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1369785575',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Berke',
    pageId: 1710466,
    revisionId: 1369785575,
    originalTitle: 'Berke',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Berke?action=history',
  },
  'wiki-berke-mn': {
    kind: 'wikipedia',
    title: 'ᠪᠡᠷᠬᠡ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠪᠡᠷᠬᠡ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=834566',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%91%D1%8D%D1%80%D1%85',
    pageId: 8173,
    revisionId: 834566,
    originalTitle: 'Бэрх',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://mn.wikipedia.org/wiki/%D0%91%D1%8D%D1%80%D1%85?action=history',
  },
  'wiki-tumbinai-en': {
    kind: 'wikipedia',
    title: 'ᠲᠤᠮᠪᠢᠨᠠᠢ ᠰᠡᠴᠡᠨ · ᠠᠩᠭᠯᠢ',
    name: 'ᠲᠤᠮᠪᠢᠨᠠᠢ ᠰᠡᠴᠡᠨ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1358737261',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Tumbinai_Khan',
    pageId: 71618969,
    revisionId: 1358737261,
    originalTitle: 'Tumbinai Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Tumbinai_Khan?action=history',
  },
  'wiki-tumbinai-mn': {
    kind: 'wikipedia',
    title: 'ᠲᠤᠮᠪᠢᠨᠠᠢ ᠰᠡᠴᠡᠨ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠲᠤᠮᠪᠢᠨᠠᠢ ᠰᠡᠴᠡᠨ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=811879',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D1%83%D0%BC%D0%B1%D0%B8%D0%BD%D0%B0%D0%B9_%D1%81%D1%8D%D1%86%D1%8D%D0%BD',
    pageId: 28338,
    revisionId: 811879,
    originalTitle: 'Тумбинай сэцэн',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A2%D1%83%D0%BC%D0%B1%D0%B8%D0%BD%D0%B0%D0%B9_%D1%81%D1%8D%D1%86%D1%8D%D0%BD?action=history',
  },
  'wiki-khabul-en': {
    kind: 'wikipedia',
    title: 'ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ · ᠠᠩᠭᠯᠢ',
    name: 'ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1375704495',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Khabul_Khan',
    pageId: 9577010,
    revisionId: 1375704495,
    originalTitle: 'Khabul Khan',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Khabul_Khan?action=history',
  },
  'wiki-khabul-mn': {
    kind: 'wikipedia',
    title: 'ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠬᠠᠪᠤᠯ ᠬᠠᠭᠠᠨ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=830680',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%A5%D0%B0%D0%B1%D1%83%D0%BB_%D1%85%D0%B0%D0%BD',
    pageId: 10405,
    revisionId: 830680,
    originalTitle: 'Хабул хан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%A5%D0%B0%D0%B1%D1%83%D0%BB_%D1%85%D0%B0%D0%BD?action=history',
  },
  'wiki-bartan-mn': {
    kind: 'wikipedia',
    title: 'ᠪᠠᠷᠲᠠᠨ ᠪᠠᠭᠠᠲᠤᠷ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠪᠠᠷᠲᠠᠨ ᠪᠠᠭᠠᠲᠤᠷ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=872171',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D1%82%D0%B0%D0%BD_%D0%B1%D0%B0%D0%B0%D1%82%D0%B0%D1%80',
    pageId: 10424,
    revisionId: 872171,
    originalTitle: 'Бартан баатар',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%91%D0%B0%D1%80%D1%82%D0%B0%D0%BD_%D0%B1%D0%B0%D0%B0%D1%82%D0%B0%D1%80?action=history',
  },
  'wiki-ayushiridara-en': {
    kind: 'wikipedia',
    title: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ · ᠠᠩᠭᠯᠢ',
    name: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1365692672',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Biligt%C3%BC_Khan_Ayushiridara',
    pageId: 572720,
    revisionId: 1365692672,
    originalTitle: 'Biligtü Khan Ayushiridara',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Biligt%C3%BC_Khan_Ayushiridara?action=history',
  },
  'wiki-ayushiridara-mn': {
    kind: 'wikipedia',
    title: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠠᠶᠤᠱᠢᠷᠢᠳᠠᠷ᠎ᠠ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=840604',
    canonicalUrl:
      'https://mn.wikipedia.org/wiki/%D0%90%D1%8E%D1%83%D1%88%D1%80%D0%B8%D0%B4%D0%B0%D1%80_%D1%85%D0%B0%D0%B0%D0%BD',
    pageId: 24318,
    revisionId: 840604,
    originalTitle: 'Аюушридар хаан',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl:
      'https://mn.wikipedia.org/wiki/%D0%90%D1%8E%D1%83%D1%88%D1%80%D0%B8%D0%B4%D0%B0%D1%80_%D1%85%D0%B0%D0%B0%D0%BD?action=history',
  },
  'wiki-maidarbal-en': {
    kind: 'wikipedia',
    title: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ · ᠠᠩᠭᠯᠢ',
    name: 'ᠮᠠᠶᠢᠳᠠᠷᠪᠠᠯ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1358812690',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Maidilibala',
    pageId: 71097124,
    revisionId: 1358812690,
    originalTitle: 'Maidilibala',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Maidilibala?action=history',
  },
  'wiki-hongwu-en': {
    kind: 'wikipedia',
    title: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ · ᠠᠩᠭᠯᠢ',
    name: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ · ᠠᠩᠭᠯᠢ',
    url: 'https://en.wikipedia.org/w/index.php?oldid=1377364608',
    canonicalUrl: 'https://en.wikipedia.org/wiki/Hongwu_Emperor',
    pageId: 163029,
    revisionId: 1377364608,
    originalTitle: 'Hongwu Emperor',
    language: 'en',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://en.wikipedia.org/wiki/Hongwu_Emperor?action=history',
  },
  'wiki-hongwu-mn': {
    kind: 'wikipedia',
    title: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ · ᠮᠣᠩᠭᠣᠯ',
    name: 'ᠮᠢᠩ ᠦᠨ ᠲᠠᠢᠵᠦ · ᠮᠣᠩᠭᠣᠯ',
    url: 'https://mn.wikipedia.org/w/index.php?oldid=854823',
    canonicalUrl: 'https://mn.wikipedia.org/wiki/%D0%A5%D1%83%D0%BD%D1%8A%D2%AF',
    pageId: 35807,
    revisionId: 854823,
    originalTitle: 'Хунъү',
    language: 'mn',
    retrievedAt: '2026-10-07T15:15:28.726502+00:00',
    license: {
      name: 'CC BY-SA 4.0',
      url: 'https://creativecommons.org/licenses/by-sa/4.0/',
    },
    attributionUrl: 'https://mn.wikipedia.org/wiki/%D0%A5%D1%83%D0%BD%D1%8A%D2%AF?action=history',
  },
});
// End Wikipedia source revisions.
