export const calendarConfig = {
  calendarSystem: 'chinese-lunisolar',
  timeZone: 'Asia/Shanghai',
  minDate: '1901-01-01',
  maxDate: '2100-12-31',
};
export const calendarCopy = {
  today: 'ᠥᠨᠥᠳᠥᠷ',
  year: 'ᠣᠨ',
  month: 'ᠰᠠᠷ᠎ᠠ',
  day: 'ᠡᠳᠦᠷ',
  choose: 'ᠡᠳᠦᠷ ᠰᠣᠩᠭᠣᠬᠤ',
  gregorian: 'ᠠᠷᠭ᠎ᠠ ᠶᠢᠨ ᠲᠣᠭᠠᠯᠠᠯ',
  lunar: 'ᠪᠢᠯᠢᠭ ᠦᠨ ᠲᠣᠭᠠᠯᠠᠯ',
  leapMonth: 'ᠢᠯᠡᠭᠦᠦ ᠰᠠᠷ᠎ᠠ',
  week: 'ᠳᠣᠯᠣᠭᠠᠨ ᠬᠣᠨᠣᠭ',
  agenda: 'ᠲᠥᠯᠥᠪᠯᠡᠭᠡ',
  add: 'ᠨᠡᠮᠡᠬᠦ',
  edit: 'ᠵᠠᠰᠠᠬᠤ',
  save: 'ᠬᠠᠳᠠᠭᠠᠯᠠᠬᠤ',
  delete: 'ᠬᠠᠰᠤᠬᠤ',
  undo: 'ᠪᠤᠴᠠᠭᠠᠬᠤ',
  title: 'ᠭᠠᠷᠴᠠᠭ',
  notes: 'ᠲᠡᠮᠳᠡᠭᠯᠡᠯ',
  location: 'ᠭᠠᠵᠠᠷ',
  start: 'ᠡᠬᠢᠯᠡᠬᠦ',
  end: 'ᠳᠠᠭᠤᠰᠬᠤ',
  time: 'ᠴᠠᠭ',
  allDay: 'ᠪᠦᠲᠦᠨ ᠡᠳᠦᠷ',
  repeat: 'ᠳᠠᠪᠲᠠᠬᠤ',
  once: 'ᠨᠢᠭᠡ ᠤᠳᠠᠭ᠎ᠠ',
  thisOccurrence: 'ᠡᠨᠡ ᠤᠳᠠᠭ᠎ᠠ',
  series: 'ᠪᠦᠬᠦ ᠳᠠᠪᠲᠠᠯᠲᠠ',
  until: 'ᠳᠠᠭᠤᠰᠬᠤ ᠡᠳᠦᠷ',
  interval: 'ᠵᠠᠪᠰᠠᠷ',
  empty: 'ᠲᠥᠯᠥᠪᠯᠡᠭᠡ ᠦᠭᠡᠢ',
  invalid: 'ᠣᠷᠣᠭᠤᠯᠤᠭᠰᠠᠨ ᠵᠦᠢᠯ ᠢᠶᠡᠨ ᠰᠢᠯᠭᠠᠨ᠎ᠠ ᠤᠤ',
  import: 'ᠣᠷᠣᠭᠤᠯᠬᠤ',
  export: 'ᠭᠠᠷᠭᠠᠬᠤ',
  imported: 'ᠣᠷᠣᠭᠤᠯᠪᠠ',
  importError: 'ᠤᠩᠰᠢᠵᠤ ᠴᠢᠳᠠᠭᠰᠠᠨ ᠦᠭᠡᠢ',
  storageError: 'ᠬᠠᠳᠠᠭᠠᠯᠠᠵᠤ ᠴᠢᠳᠠᠭᠰᠠᠨ ᠦᠭᠡᠢ',
  appearance: 'ᠵᠠᠭᠪᠤᠷ',
  light: 'ᠭᠡᠭᠡᠨ',
  dark: 'ᠬᠠᠷᠠᠩᠭᠤᠢ',
  paper: 'ᠴᠠᠭᠠᠰᠤ',
  ink: 'ᠬᠠᠷ᠎ᠠ ᠴᠠᠭᠠᠨ',
  firstWeekday: 'ᠡᠬᠢᠯᠡᠬᠦ ᠭᠠᠷᠠᠭ',
  display: 'ᠬᠠᠷᠠᠭᠳᠠᠴᠠ',
  weekdays: ['ᠳᠠᠸᠠ', 'ᠮᠢᠭᠮᠠᠷ', 'ᡀᠠᠭᠪᠠ', 'ᠫᠦᠷᠪᠦ', 'ᠪᠠᠰᠠᠩ', 'ᠪᠢᠮᠪᠠ', 'ᠨᠢᠮ᠎ᠠ'],
};
