// Product language: Traditional Mongolian used in Inner Mongolia.
// Linguistic review is tracked separately in docs/ui-copy-review.json.
export const uiLocale = 'mn-Mong-CN';

export const labels = {
  brand: 'ᠨᠤᠲᠤᠭ',
  previous: 'ᠡᠮᠦᠨᠡᠬᠢ',
  next: 'ᠳᠠᠷᠠᠭᠠᠬᠢ',
  people: 'ᠬᠦᠮᠦᠰ',
  tribes: 'ᠠᠶᠢᠮᠠᠭ',
  library: 'ᠮᠡᠳᠡᠯᠭᠡ',
  calendar: 'ᠴᠠᠭ ᠲᠣᠭ᠎ᠠ',
  chronicle: 'ᠲᠡᠦᠬᠡ',
  search: 'ᠬᠠᠶᠢᠬᠤ',
  close: 'ᠬᠠᠭᠠᠬᠤ',
  clear: 'ᠠᠷᠢᠯᠭᠠᠬᠤ',
  read: 'ᠤᠩᠰᠢᠬᠤ',
  settings: 'ᠲᠣᠬᠢᠷᠠᠭᠤᠯᠭ᠎ᠠ',
  type: 'ᠦᠰᠦᠭ ᠦᠨ ᠬᠡᠮᠵᠢᠶ᠎ᠡ',
  larger: 'ᠲᠣᠮᠣᠳᠬᠠᠬᠤ',
  smaller: 'ᠪᠠᠭᠠᠰᠬᠠᠬᠤ',
  fit: 'ᠪᠦᠬᠦᠨ ᠢ ᠦᠵᠡᠭᠦᠯᠬᠦ',
  focus: 'ᠲᠥᠪᠯᠡᠷᠡᠭᠦᠯᠬᠦ',
  details: 'ᠳᠡᠯᠭᠡᠷᠡᠩᠭᠦᠢ',
  sources: 'ᠰᠤᠷᠪᠤᠯᠵᠢ',
  relations: 'ᠬᠠᠷᠢᠯᠴᠠᠭ᠎ᠠ',
  all: 'ᠪᠦᠬᠦ',
  family: 'ᠤᠷᠤᠭ ᠲᠥᠷᠥᠯ',
  power: 'ᠤᠯᠤᠰ ᠲᠥᠷᠥ',
  timeline: 'ᠣᠨ ᠴᠠᠭ',
  back: 'ᠪᠤᠴᠠᠬᠤ',
  more: 'ᠨᠡᠮᠡᠵᠦ ᠦᠵᠡᠬᠦ',
  retry: 'ᠳᠠᠬᠢᠨ ᠣᠷᠣᠯᠳᠤᠬᠤ',
  update: 'ᠰᠢᠨᠡᠴᠢᠯᠡᠬᠦ',
  download: 'ᠲᠠᠲᠠᠵᠤ ᠠᠪᠬᠤ',
  saved: 'ᠬᠠᠳᠠᠭᠠᠯᠠᠪᠠ',
  connection: 'ᠰᠦᠯᠵᠢᠶ᠎ᠡ',
  directions: 'ᠵᠦᠭ',
  explore: 'ᠰᠡᠳᠦᠪ',
  catalog: 'ᠭᠠᠷᠴᠠᠭ',
};
